namespace Microsoft.Xna.Framework {
 public record struct Vector2(float X,float Y){public static Vector2 Zero=>new(0,0);public static Vector2 UnitY=>new(0,1);public static Vector2 operator +(Vector2 a,Vector2 b)=>new(a.X+b.X,a.Y+b.Y);public static Vector2 operator -(Vector2 a,Vector2 b)=>new(a.X-b.X,a.Y-b.Y);public static Vector2 operator *(Vector2 a,float b)=>new(a.X*b,a.Y*b);public float Length()=>MathF.Sqrt(X*X+Y*Y);public float ToRotation()=>MathF.Atan2(Y,X);public Vector2 SafeNormalize(Vector2 fallback)=>Length()>0?this*(1/Length()):fallback;public Vector2 RotatedBy(float angle)=>new(X*MathF.Cos(angle)-Y*MathF.Sin(angle),X*MathF.Sin(angle)+Y*MathF.Cos(angle));public static Vector2 Lerp(Vector2 a,Vector2 b,float t)=>a+(b-a)*t;public static float DistanceSquared(Vector2 a,Vector2 b){var d=a-b;return d.X*d.X+d.Y*d.Y;}}
 public record struct Rectangle(int X,int Y,int Width,int Height);public struct Color{public static Color LightGreen=>new();public static Color operator *(Color c,float f)=>c;}
}
namespace Microsoft.Xna.Framework.Graphics {public enum SpriteEffects{None}public class SpriteBatch{public int Calls;public void Draw(object pixel,Microsoft.Xna.Framework.Rectangle box,Microsoft.Xna.Framework.Color color)=>Calls++;public void Draw(object pixel,Microsoft.Xna.Framework.Vector2 pos,object rect,Microsoft.Xna.Framework.Color color,float angle,Microsoft.Xna.Framework.Vector2 origin,Microsoft.Xna.Framework.Vector2 scale,SpriteEffects effects,float depth)=>Calls++;}}
namespace Terraria {
 public static class Main{public static int netMode,myPlayer,maxPlayers=2,maxNPCs=3;public static bool dedServ;public static Player[] player=[new(),new()];public static NPC[] npc=[new(),new(),new()];public static Microsoft.Xna.Framework.Vector2 screenPosition;public static Microsoft.Xna.Framework.Graphics.SpriteBatch spriteBatch=new();}
 public class Player{public bool active=true,dead;public int direction=1;public Microsoft.Xna.Framework.Vector2 Center,velocity;public Microsoft.Xna.Framework.Vector2 Bottom=>Center+new Microsoft.Xna.Framework.Vector2(0,20);public int Buff,Duration;public struct HurtInfo{}public void AddBuff(int type,int time){Buff=type;Duration=time;}}
 public class NPC{public bool active=true,netUpdate;public int life=2800,lifeMax=2800,damage=28,whoAmI,target,DespawnCalls;public float rotation;public float[] ai=new float[4],localAI=new float[4];public Microsoft.Xna.Framework.Vector2 Center,velocity;public Microsoft.Xna.Framework.Rectangle Hitbox=>new(0,0,96,96);public Terraria.ModLoader.ModNPC ModNPC;public object GetSource_FromAI()=>null;public void EncourageDespawn(int time)=>DespawnCalls++;public void TargetClosest(bool face){target=255;for(int i=0;i<Main.maxPlayers;i++)if(Main.player[i].active&&!Main.player[i].dead){target=i;break;}}}
 public class Projectile{public int width,height,penetrate,timeLeft,owner;public bool hostile,friendly,tileCollide,ignoreWater,netImportant,netUpdate,active=true;public float[] ai=new float[3];public Microsoft.Xna.Framework.Vector2 Center,position,velocity;public static List<(Microsoft.Xna.Framework.Vector2 Position,int Type,int Damage,float Source,float Session)> Spawned=new();public void Kill()=>active=false;public static int NewProjectile(object source,Microsoft.Xna.Framework.Vector2 pos,Microsoft.Xna.Framework.Vector2 velocity,int type,int damage,float kb,int owner,float ai0=0,float ai1=0){Spawned.Add((pos,type,damage,ai0,ai1));return Spawned.Count-1;}}
 public static class Collision{public static bool Blocked;public static bool CanHitLine(Microsoft.Xna.Framework.Vector2 a,int w,int h,Microsoft.Xna.Framework.Vector2 b,int w2,int h2)=>!Blocked;}
 public static class CombatText{public static int Calls;public static void NewText(Microsoft.Xna.Framework.Rectangle r,Microsoft.Xna.Framework.Color c,string text)=>Calls++;}
 public static class Lighting{public static int Calls;public static void AddLight(Microsoft.Xna.Framework.Vector2 pos,float r,float g,float b)=>Calls++;}
}
namespace Terraria.ID {public static class NetmodeID{public const int MultiplayerClient=1,Server=2;}public static class BuffID{public const int Poisoned=20;}}
namespace Terraria.Localization{public static class Language{public static string GetTextValue(string key)=>key;}}
namespace Terraria.GameContent{public static class TextureAssets{public static Asset MagicPixel=new();public class Asset{public object Value=>new();}}}
namespace Terraria.ModLoader{
 public class ModNPC{public Terraria.NPC NPC=new();public virtual void AI(){}public virtual void SendExtraAI(System.IO.BinaryWriter w){}public virtual void ReceiveExtraAI(System.IO.BinaryReader r){}public virtual bool CanHitPlayer(Terraria.Player p,ref int slot)=>true;public virtual bool PreDraw(Microsoft.Xna.Framework.Graphics.SpriteBatch b,Microsoft.Xna.Framework.Vector2 p,Microsoft.Xna.Framework.Color c)=>true;}
 public class ModProjectile{public Terraria.Projectile Projectile=new();public virtual string Texture=>"";public virtual void SetDefaults(){}public virtual void AI(){}public virtual void SendExtraAI(System.IO.BinaryWriter w){}public virtual void ReceiveExtraAI(System.IO.BinaryReader r){}public virtual bool? CanDamage()=>null;public virtual bool CanHitPlayer(Terraria.Player p)=>true;public virtual void OnHitPlayer(Terraria.Player p,Terraria.Player.HurtInfo i){}public virtual bool PreDraw(ref Microsoft.Xna.Framework.Color c)=>true;}
 public static class ModContent{public static int ProjectileType<T>()=>typeof(T).Name=="GardenBriarPatch"?2:1;}
}
namespace XianXia.Content.NPCs.Bosses{public partial class GardenWarden:Terraria.ModLoader.ModNPC{}}
namespace XianXia.Content.Projectiles{public class BossSpiritBoltProjectile{}}
