<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings></PropertyGroup><ItemGroup><Compile Include="../Companions/Stubs.cs" Link="Stubs.cs"/><Compile Include="../../../Content/Items/HandGenerated/BlackFurnaceIronGolemPet.cs" Link="BlackFurnaceIronGolemPet.cs"/><Compile Include="../../../Content/Buffs/BlackFurnaceIronGolemPetBuff.cs" Link="BlackFurnaceIronGolemPetBuff.cs"/><Compile Include="../../../Content/Projectiles/BlackFurnaceIronGolemPetProjectile.cs" Link="BlackFurnaceIronGolemPetProjectile.cs"/><Compile Include="../../../Content/Items/HandGenerated/SmallTabletPet.cs" Link="SmallTabletPet.cs"/><Compile Include="../../../Content/Buffs/SmallTabletPetBuff.cs" Link="SmallTabletPetBuff.cs"/><Compile Include="../../../Content/Projectiles/SmallTabletPetProjectile.cs" Link="SmallTabletPetProjectile.cs"/></ItemGroup></Project>