using Microsoft.Xna.Framework;using Terraria;using Terraria.ID;using XianXia.Content.NPCs.Bosses;
int checks=0;void Check(bool value,string message){checks++;if(!value)throw new Exception(message);}
BlackFurnaceIronGolem Setup(int count=0){Main.netMode=NetmodeID.Server;Main.player=[new(){Center=new(100,0)},new(){Center=new(200,0)}];Main.npc=Enumerable.Range(0,Main.maxNPCs).Select(i=>new NPC{whoAmI=i}).ToArray();Main.rand=new();NPC.Calls=0;NPC.FailureResult=int.MinValue;var boss=new BlackFurnaceIronGolem();boss.NPC=Main.npc[0];boss.NPC.active=true;boss.NPC.type=9;for(int index=1;index<=count;index++){Main.npc[index].active=true;Main.npc[index].type=7;}return boss;}
foreach(int initial in new[]{0,1,2,3,4,5,6,7,10}){var boss=Setup(initial);boss.SpawnShardAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==initial+Math.Max(0,Math.Min(2,6-initial)),"Per-pattern batch respects nearby cap");Check(NPC.Calls==Math.Max(0,Math.Min(2,6-initial)),"Cap prevents even attempted spawn");foreach(var created in Main.ActiveNPCs.Where(n=>n.type==7&&n.netUpdate))Check(created.target==boss.NPC.target&&created.ai[0]==0,"New shard retains parent slot and target and is synchronized");}
var repeated=Setup();for(int wave=0;wave<100;wave++){repeated.SpawnShardAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)<=6,"Long fight never exceeds six nearby shards");}Check(NPC.Calls==6,"Repeated full waves do not call spawner");Main.npc[1].active=false;Main.npc[2].active=false;repeated.SpawnShardAdds();Check(NPC.Calls==8&&Main.ActiveNPCs.Count(n=>n.type==7)==6,"Dead shard slots permit bounded replenishment");
foreach(float distance in new[]{1599f,1600f,1601f}){var boss=Setup(6);Main.npc[6].Center=new(distance,0);boss.SpawnShardAdds();Check(NPC.Calls==(distance<=1600?0:1),"Exact arena boundary counts natural shards");}
var unrelated=Setup(6);foreach(var npc in Main.npc.Skip(1).Take(6))npc.type=8;unrelated.SpawnShardAdds();Check(NPC.Calls==2,"Other enemy types do not fill shard cap");
var expired=Setup(6);Main.npc[1].life=0;expired.SpawnShardAdds();Check(NPC.Calls==1,"Active zero-life shard does not consume combat quota");
foreach(int failure in new[]{-1,Main.maxNPCs,int.MaxValue}){var boss=Setup();NPC.FailureResult=failure;boss.SpawnShardAdds();Check(NPC.Calls==1&&Main.ActiveNPCs.Count()==1,"Failed creation stops batch without indexing sentinel");}
var full=Setup();foreach(var npc in Main.npc.Skip(1)){npc.active=true;npc.type=8;}full.SpawnShardAdds();Check(NPC.Calls==1,"Full NPC table stops safely");
var wrong=Setup();Main.npc[1].active=true;Main.npc[1].type=8;NPC.FailureResult=1;wrong.SpawnShardAdds();Check(NPC.Calls==1&&!Main.npc[1].netUpdate,"Returned unrelated NPC cannot receive shard synchronization");
foreach(Action<BlackFurnaceIronGolem> invalidate in new Action<BlackFurnaceIronGolem>[] {b=>Main.netMode=NetmodeID.MultiplayerClient,b=>b.NPC.active=false,b=>b.NPC.life=0,b=>b.NPC.target=-1,b=>Main.player[0].dead=true,b=>Main.player[0].active=false,b=>Main.player[0].Center=new(5000,0),b=>b.NPC.Center=new(float.NaN,0)}){var boss=Setup();invalidate(boss);boss.SpawnShardAdds();Check(NPC.Calls==0&&Main.rand.Calls==0,"Invalid battle/client produces no summons or spawn RNG");}
var charging=Setup();charging.NPC.ai[1]=179;Check(charging.UpdateFurnaceCharge(Main.player[0],true)&&charging.NPC.netUpdate,"furnace begins synchronized charge warning");float locked=charging.NPC.ai[3];Main.player[0].Center=new(0,100);for(int tick=1;tick<40;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.ai[3]==locked&&charging.NPC.velocity.X==0,"warning locks aim and avoids rushing");charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.velocity.X==14&&charging.NPC.velocity.Y==0,"dash follows locked direction despite player movement");for(int tick=1;tick<24;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.velocity.X<14,"dash enters recovery after twenty-four ticks");for(int tick=1;tick<40;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.ai[1]==0&&charging.NPC.ai[0]==0&&charging.NPC.ai[2]==0,"recovery resets attack cooldowns");var clientCharge=Setup();Main.netMode=1;clientCharge.NPC.ai[1]=179;Check(!clientCharge.UpdateFurnaceCharge(Main.player[0],true)&&clientCharge.NPC.ai[1]==179,"client cannot begin charge");clientCharge.NPC.ai[1]=-41;Check(clientCharge.UpdateFurnaceCharge(Main.player[0],true)&&clientCharge.NPC.ai[1]==-41,"client follows synchronized phase without advancing it");
foreach(int mode in new[]{0,1,2})foreach(float bad in new[]{float.NaN,float.PositiveInfinity,-105f,181f}){var malformed=Setup();Main.netMode=mode;malformed.NPC.ai[1]=bad;Check(malformed.UpdateFurnaceCharge(Main.player[0],true),"bad charge state blocks normal attack frame");Check(malformed.NPC.velocity==Microsoft.Xna.Framework.Vector2.Zero,"bad charge state stops movement");Check(mode==1||malformed.NPC.ai[1]==0,"authority repairs bad charge state");}
var drawn=Setup();drawn.NPC.ai[1]=-10;var batch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;drawn.PreDraw(batch,new(0,0),default);Check(batch.Calls==0,"dedicated charge skips corridor graphics");Main.dedServ=false;drawn.PreDraw(batch,new(0,0),default);Check(batch.Calls==3&&batch.LastScale.X==432,"charge warning corridor covers dash distance plus hitbox");drawn.NPC.ai[1]=-41;drawn.PreDraw(batch,new(0,0),default);Check(batch.Calls==3,"charge corridor only during warning");
foreach(int phase in new[]{-10,-41,-70})foreach(bool replace in new[]{false,true}){var switching=Setup();switching.NPC.ai[1]=179;switching.UpdateFurnaceCharge(Main.player[0],true);switching.NPC.ai[1]=phase;switching.NPC.netUpdate=false;if(replace)Main.player[0]=new(){Center=new(100,0)};else switching.NPC.target=1;Check(switching.UpdateFurnaceCharge(Main.player[switching.NPC.target],true),"furnace consumes retarget cancellation frame");Check(switching.NPC.ai[1]==0&&switching.NPC.ai[0]==0&&switching.NPC.ai[2]==0,"retarget clears charge and attack timers");Check(switching.NPC.velocity==Microsoft.Xna.Framework.Vector2.Zero&&switching.NPC.netUpdate,"retarget stops and synchronizes charge");switching.UpdateFurnaceCharge(Main.player[switching.NPC.target],true);Check(switching.NPC.ai[1]==1,"retarget restarts full warning cooldown");}
var contactBoss=Setup();int slot=0;contactBoss.NPC.ai[1]=179;for(int frame=1;frame<=104;frame++){contactBoss.UpdateFurnaceCharge(Main.player[0],true);Check(contactBoss.CanHitPlayer(Main.player[0],ref slot)==(frame>40&&frame<=64),"furnace contact matches exact charge frame "+frame);}contactBoss.UpdateFurnaceCharge(Main.player[0],true);Check(contactBoss.CanHitPlayer(Main.player[0],ref slot),"normal contact returns after full recovery");Collision.Blocked=true;Check(!contactBoss.CanHitPlayer(Main.player[0],ref slot),"furnace wall blocks contact");Collision.Blocked=false;Main.player[1].Center=new(float.NaN,0);Check(!contactBoss.CanHitPlayer(Main.player[1],ref slot),"furnace cannot hit nonfinite secondary player");
foreach(int spokes in new[]{6,8,12}){Setup();Projectile.Shots.Clear();var moon=new MoonboneImmortal();moon.NPC=Main.npc[0];moon.NPC.ai[2]=(spokes==12?150:spokes==8?210:270)-45;moon.UpdateMoonRing(Main.player[0],spokes>=8,spokes==12);float aim=moon.NPC.ai[3];Main.player[0].Center=new(0,100);for(int tick=1;tick<44;tick++)moon.UpdateMoonRing(Main.player[0],spokes>=8,spokes==12);Check(Projectile.Shots.Count==0,"moon ring waits full warning");moon.UpdateMoonRing(Main.player[0],spokes>=8,spokes==12);Check(Projectile.Shots.Count(s=>s.Type==1)==spokes-1,"moon ring leaves one empty spoke");Check(moon.NPC.ai[3]==aim&&moon.NPC.ai[2]==-30,"moon locks safe direction then recovers");for(int tick=0;tick<30;tick++)moon.UpdateMoonRing(Main.player[0],spokes>=8,spokes==12);Check(moon.NPC.ai[2]==0,"moon recovery lasts thirty ticks");}
Setup();Projectile.Shots.Clear();var moonClient=new MoonboneImmortal();moonClient.NPC=Main.npc[0];moonClient.NPC.ai[1]=20;moonClient.NPC.ai[2]=225;Main.netMode=1;moonClient.UpdateMoonRing(Main.player[0],false,false);Check(moonClient.NPC.ai[1]==20&&Projectile.Shots.Count==0,"moon client cannot advance warning or fire");var moonBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;moonClient.PreDraw(moonBatch,new(0,0),default);Check(moonBatch.Calls==0,"moon dedicated warning avoids graphics");Main.dedServ=false;moonClient.PreDraw(moonBatch,new(0,0),default);Check(moonBatch.Calls==2,"moon opening has two visible boundaries");Setup();Projectile.Shots.Clear();var crossingMoon=new MoonboneImmortal();crossingMoon.NPC=Main.npc[0];crossingMoon.NPC.ai[2]=225;crossingMoon.UpdateMoonRing(Main.player[0],false,false);for(int tick=1;tick<44;tick++)crossingMoon.UpdateMoonRing(Main.player[0],true,true);Check(Projectile.Shots.Count==0,"moon health phase transition keeps full warning");crossingMoon.UpdateMoonRing(Main.player[0],true,true);Check(Projectile.Shots.Count(s=>s.Type==1)==11,"moon phase transition releases current phase ring after warning");
foreach(int mode in new[]{0,1,2})foreach(int channel in new[]{1,2})foreach(float bad in new[]{float.NaN,float.PositiveInfinity,-31f,271f,0.5f}){Setup();Projectile.Shots.Clear();var badMoon=new MoonboneImmortal();badMoon.NPC=Main.npc[0];badMoon.NPC.ai[channel]=bad;Main.netMode=mode;Check(badMoon.UpdateMoonRing(Main.player[0],false,false),"bad moon state consumes frame");int hitSlot=0;Check(!badMoon.CanHitPlayer(Main.player[0],ref hitSlot)&&Projectile.Shots.Count==0,"bad moon state harmless and cannot fire");Check(mode==1||badMoon.NPC.ai[1]==0&&badMoon.NPC.ai[2]==0,"authority repairs moon timers");}
Setup();var contactMoon=new MoonboneImmortal();contactMoon.NPC=Main.npc[0];contactMoon.NPC.ai[2]=225;int moonSlot=0;for(int frame=1;frame<=75;frame++){contactMoon.UpdateMoonRing(Main.player[0],false,false);Check(!contactMoon.CanHitPlayer(Main.player[0],ref moonSlot),"moon warning and complete recovery harmless "+frame);}contactMoon.UpdateMoonRing(Main.player[0],false,false);Check(contactMoon.CanHitPlayer(Main.player[0],ref moonSlot),"moon normal contact resumes after recovery");Collision.Blocked=true;Check(!contactMoon.CanHitPlayer(Main.player[0],ref moonSlot),"moon wall prevents contact");Collision.Blocked=false;
foreach(int failure in new[]{-1,Main.maxNPCs,int.MaxValue,0}){Setup();var quotaMoon=new MoonboneImmortal();quotaMoon.NPC=Main.npc[0];NPC.FailureResult=failure;quotaMoon.SpawnMoonAdds();Check(NPC.Calls==1,"moon failed creation stops batch");NPC.FailureResult=int.MinValue;quotaMoon.SpawnMoonAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==2,"moon retries complete quota after failure");int createdCalls=NPC.Calls;foreach(var add in Main.ActiveNPCs.Where(n=>n.type==7)){Check(add.target==quotaMoon.NPC.target&&add.netUpdate,"moon add inherits synchronized target");add.active=false;}quotaMoon.SpawnMoonAdds();Check(NPC.Calls==createdCalls,"moon killed adds never replenish quota");}
Setup();var partialMoon=new MoonboneImmortal();partialMoon.NPC=Main.npc[0];foreach(var occupied in Main.npc.Skip(2)){occupied.active=true;occupied.type=8;}partialMoon.SpawnMoonAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==1,"moon partial creation counts one successful add");Main.npc[2].active=false;partialMoon.SpawnMoonAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==2,"moon retry fills only missing add");foreach(Action<MoonboneImmortal> invalidate in new Action<MoonboneImmortal>[] {m=>Main.netMode=1,m=>m.NPC.active=false,m=>Main.player[0].dead=true,m=>m.NPC.target=255}){Setup();var deniedMoon=new MoonboneImmortal();deniedMoon.NPC=Main.npc[0];invalidate(deniedMoon);deniedMoon.SpawnMoonAdds();Check(NPC.Calls==0&&Main.rand.Calls==0,"invalid moon battle or client cannot summon");}
foreach(int mode in new[]{0,2})foreach(bool recovery in new[]{false,true})foreach(bool replaceObject in new[]{false,true}) {
 Setup();Projectile.Shots.Clear();var switchingMoon=new MoonboneImmortal{NPC=Main.npc[0]};Main.netMode=mode;switchingMoon.NPC.ai[2]=225;
 switchingMoon.UpdateMoonRing(Main.player[0],false,false);
 if(recovery)for(int frame=1;frame<45;frame++)switchingMoon.UpdateMoonRing(Main.player[0],false,false);
 int shots=Projectile.Shots.Count;if(replaceObject)Main.player[0]=new(){Center=new(0,200)};else {switchingMoon.NPC.target=1;Main.player[1].Center=new(0,200);}
 switchingMoon.NPC.netUpdate=false;switchingMoon.NPC.velocity=new(5,5);
 Check(switchingMoon.UpdateMoonRing(Main.player[switchingMoon.NPC.target],false,false),"Moon target change consumes cancellation frame");
 Check(switchingMoon.NPC.ai.All(v=>v==0)&&switchingMoon.NPC.netUpdate&&switchingMoon.NPC.velocity.X==0&&switchingMoon.NPC.velocity.Y==0,"Moon changed target resets locks stops movement and synchronizes");
 int cancelSlot=0;Check(!switchingMoon.CanHitPlayer(Main.player[switchingMoon.NPC.target],ref cancelSlot)&&Projectile.Shots.Count==shots,"Moon cancellation frame has no contact or additional ring");
 for(int frame=0;frame<225;frame++)switchingMoon.UpdateMoonRing(Main.player[switchingMoon.NPC.target],false,false);
 Check(switchingMoon.NPC.ai[1]==0&&Projectile.Shots.Count==shots,"Moon replacement target gets full normal interval before new warning");
 for(int frame=0;frame<44;frame++)switchingMoon.UpdateMoonRing(Main.player[switchingMoon.NPC.target],false,false);
 Check(switchingMoon.NPC.ai[1]==1&&Projectile.Shots.Count==shots,"Moon replacement target gets complete forty-five tick warning");
 Check(Math.Abs(switchingMoon.NPC.ai[3]-MathF.PI/2)<.0001f,"Moon restarted warning locks replacement position instead of stale direction");
 switchingMoon.UpdateMoonRing(Main.player[switchingMoon.NPC.target],false,false);Check(Projectile.Shots.Count==shots+5,"Moon new target ring only releases after full restart and warning");
}
foreach(bool recovery in new[]{false,true}) {
 Setup();Projectile.Shots.Clear();var waitingMoon=new MoonboneImmortal{NPC=Main.npc[0]};waitingMoon.NPC.ai[2]=225;waitingMoon.UpdateMoonRing(Main.player[0],false,false);
 if(recovery)for(int frame=1;frame<45;frame++)waitingMoon.UpdateMoonRing(Main.player[0],false,false);
 float[] before=waitingMoon.NPC.ai.ToArray();int shots=Projectile.Shots.Count;Main.netMode=1;waitingMoon.NPC.target=1;waitingMoon.NPC.netUpdate=false;
 waitingMoon.UpdateMoonRing(Main.player[1],false,false);
 Check(waitingMoon.NPC.ai.SequenceEqual(before)&&!waitingMoon.NPC.netUpdate&&Projectile.Shots.Count==shots,"Moon client waits for authority cancellation instead of restarting timers");
}
foreach((int life,int spokes) in new[]{(100,6),(70,6),(69,8),(60,8),(35,8),(34,12),(30,12),(1,12)}) {
 Setup();Main.dedServ=false;var visualMoon=new MoonboneImmortal{NPC=Main.npc[0]};visualMoon.NPC.life=life;visualMoon.NPC.lifeMax=100;visualMoon.NPC.ai[1]=20;
 var visualBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();visualMoon.PreDraw(visualBatch,new(0,0),default);
 Check(visualBatch.Calls==2&&Math.Abs(visualBatch.LastAngle-MathF.PI/spokes)<.0001f,"Moon safe-gap drawing follows actual seventy/thirty-five percent phase boundary");
}
foreach(int cloudMode in new[]{0,2}) {
 Setup();Main.netMode=cloudMode;var cloud=new TribulationCloudAvatar{NPC=Main.npc[0]};cloud.NPC.target=1;
 cloud.SpawnCloudAdd();var add=Main.npc[1];
 Check(NPC.Calls==1&&add.active&&add.type==7&&add.ai[0]==0&&add.target==1&&add.netUpdate,"Cloud add inherits parent and synchronized battle target");
 for(int wave=0;wave<20;wave++)cloud.SpawnCloudAdd();
 Check(NPC.Calls==1,"Cloud repeated patterns cannot exceed one successful creation");add.active=false;cloud.SpawnCloudAdd();Check(NPC.Calls==1,"Killed cloud add does not replenish quota");
 foreach(int failure in new[]{-1,Main.maxNPCs,int.MaxValue,0}) {
  Setup();Main.netMode=cloudMode;var retryCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};NPC.FailureResult=failure;retryCloud.SpawnCloudAdd();
  Check(NPC.Calls==1&&Main.ActiveNPCs.Count()==1,"Cloud invalid creation result consumes no successful quota");NPC.FailureResult=int.MinValue;retryCloud.SpawnCloudAdd();
  Check(NPC.Calls==2&&Main.ActiveNPCs.Count(n=>n.type==7)==1,"Cloud next pattern retries missing add once");retryCloud.SpawnCloudAdd();Check(NPC.Calls==2,"Cloud successful retry closes quota");
 }
 foreach(int badReturned in new[]{0,1,2,3}) {
  Setup();Main.netMode=cloudMode;var wrongCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};Main.npc[1]=badReturned==0?null:new NPC{active=badReturned!=1,life=badReturned==2?0:100,type=badReturned==3?8:7};NPC.FailureResult=1;wrongCloud.SpawnCloudAdd();
  Check(Main.npc[1]==null||!Main.npc[1].netUpdate,"Cloud rejects null/inactive/dead/wrong-type returned NPC without marking it");Main.npc[1]=new NPC{whoAmI=1};NPC.FailureResult=int.MinValue;wrongCloud.SpawnCloudAdd();Check(NPC.Calls==2&&Main.npc[1].netUpdate,"Malformed returned NPC does not consume cloud quota");
 }
 Setup();Main.netMode=cloudMode;var fullCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};foreach(var occupied in Main.npc.Skip(1)){occupied.active=true;occupied.type=8;}fullCloud.SpawnCloudAdd();Check(NPC.Calls==1,"Full NPC table safely discards cloud attempt");Main.npc[1].active=false;fullCloud.SpawnCloudAdd();Check(NPC.Calls==2&&Main.npc[1].type==7,"Freed NPC capacity allows next cloud pattern to complete quota");
}
foreach(Action<TribulationCloudAvatar> invalidate in new Action<TribulationCloudAvatar>[] {c=>Main.netMode=1,c=>c.NPC.active=false,c=>c.NPC.life=0,c=>c.NPC.target=-1,c=>c.NPC.target=Main.maxPlayers,c=>Main.player[0].dead=true,c=>Main.player[0].active=false,c=>Main.player[0].Center=new(5000,0),c=>c.NPC.Center=new(float.NaN,0)}) {
 Setup();var deniedCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};invalidate(deniedCloud);deniedCloud.SpawnCloudAdd();Check(NPC.Calls==0,"Invalid cloud battle/client does not attempt a summon");
}
foreach(int mode in new[]{0,2}) {
 Setup();Main.netMode=mode;var cloudCharge=new TribulationCloudAvatar{NPC=Main.npc[0]};int cooldown=0;
 for(int tick=1;tick<210;tick++)Check(!cloudCharge.UpdateCloudCharge(Main.player[0],true),"Cloud waits full 210 tick cooldown");
 Check(cloudCharge.UpdateCloudCharge(Main.player[0],true)&&cloudCharge.NPC.netUpdate,"Cloud starts synchronized warning at cooldown boundary");float cloudLocked=cloudCharge.NPC.ai[3];Main.player[0].Center=new(0,100);
 for(int frame=1;frame<=108;frame++) {
  if(frame>1)cloudCharge.UpdateCloudCharge(Main.player[0],true);
  Check(cloudCharge.CanHitPlayer(Main.player[0],ref cooldown)==(frame>45&&frame<=63),"Cloud contact only during eighteen dash frames");
  Check(cloudCharge.NPC.ai[3]==cloudLocked,"Cloud keeps warning aim through recovery");
  if(frame>45&&frame<=63)Check(cloudCharge.NPC.velocity==new Vector2(15,0),"Cloud dash follows locked direction despite movement");
 }
 Check(cloudCharge.NPC.ai[0]==0&&cloudCharge.NPC.ai[1]==0&&cloudCharge.NPC.ai[2]==0,"Cloud finishes full recovery and clears other attack timers");cloudCharge.UpdateCloudCharge(Main.player[0],true);Check(cloudCharge.CanHitPlayer(Main.player[0],ref cooldown),"Cloud normal contact resumes after recovery");
 foreach(int phase in new[]{-10,-50,-80})foreach(bool replace in new[]{false,true}) {
  Setup();Main.netMode=mode;var changedCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};changedCloud.NPC.ai[1]=209;changedCloud.UpdateCloudCharge(Main.player[0],true);changedCloud.NPC.ai[1]=phase;
  if(replace)Main.player[0]=new(){Center=new(0,100)};else changedCloud.NPC.target=1;
  Check(changedCloud.UpdateCloudCharge(Main.player[changedCloud.NPC.target],true)&&changedCloud.NPC.ai.All(v=>v==0)&&changedCloud.NPC.velocity==Vector2.Zero&&changedCloud.NPC.netUpdate,"Cloud target replacement cancels warning dash or recovery");Check(!changedCloud.CanHitPlayer(Main.player[changedCloud.NPC.target],ref cooldown),"Cloud cancellation frame remains harmless");changedCloud.UpdateCloudCharge(Main.player[changedCloud.NPC.target],true);Check(changedCloud.NPC.ai[1]==1,"Cloud retarget starts full cooldown");
 }
}
foreach(int mode in new[]{0,1,2})foreach(float bad in new[]{float.NaN,float.PositiveInfinity,-109f,211f,0.5f,-1.5f}) {
 Setup();Main.netMode=mode;var badCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};badCloud.NPC.ai[1]=bad;int cooldown=0;Check(badCloud.UpdateCloudCharge(Main.player[0],true)&&!badCloud.CanHitPlayer(Main.player[0],ref cooldown),"Cloud malformed timer cannot dash or contact");Check(mode==1||badCloud.NPC.ai.All(v=>v==0)&&badCloud.NPC.netUpdate,"Authority repairs cloud malformed timer");
}
Setup();var visualCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};visualCloud.NPC.ai[1]=209;visualCloud.UpdateCloudCharge(Main.player[0],true);var cloudBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;visualCloud.PreDraw(cloudBatch,default,default);Check(cloudBatch.Calls==0,"Cloud dedicated server avoids warning graphics");Main.dedServ=false;visualCloud.PreDraw(cloudBatch,default,default);Check(cloudBatch.Calls==3,"Cloud warning paints corridor and both edges");int cloudSlot=0;Collision.Blocked=true;for(int frame=1;frame<=45;frame++)visualCloud.UpdateCloudCharge(Main.player[0],true);Check(!visualCloud.CanHitPlayer(Main.player[0],ref cloudSlot),"Cloud dash cannot contact through wall");Collision.Blocked=false;
Setup();var waitingCloud=new TribulationCloudAvatar{NPC=Main.npc[0]};waitingCloud.NPC.ai[1]=-10;Main.netMode=1;waitingCloud.UpdateCloudCharge(Main.player[0],true);Check(waitingCloud.NPC.ai[1]==-10,"Cloud client does not advance authoritative charge clock");
foreach(int mode in new[]{0,2}) {
 Setup();Main.netMode=mode;Projectile.Shots.Clear();Projectile.Positions.Clear();var womb=new AbyssalStarWomb{NPC=Main.npc[0]};Main.player[0].velocity=new(2,3);
 for(int pattern=1;pattern<=20;pattern++){womb.ReleaseCompressionField(Main.player[0],18);Check(Projectile.Shots.Count==(pattern+1)/2,"Compression alternates eligible encounter patterns without world clock");Check(womb.NPC.ai[3]==0&&womb.NPC.netUpdate,"Compression leaves ring direction untouched");}
 Check(Projectile.Positions.All(p=>p==new Vector2(136,54)),"Compression predicts target eighteen ticks ahead");
 foreach(float angle in new[]{0f,1f,-1f,0.5f}){var directedWomb=new AbyssalStarWomb{NPC=Main.npc[0]};directedWomb.NPC.ai[3]=angle;int before=Projectile.Shots.Count;directedWomb.ReleaseCompressionField(Main.player[0],18);Check(directedWomb.NPC.ai[3]==angle&&Projectile.Shots.Count==before+1,"Compression does not overwrite ring warning angle");}
 foreach(float badVelocity in new[]{float.NaN,float.PositiveInfinity,float.MaxValue}){womb=new AbyssalStarWomb{NPC=Main.npc[0]};womb.NPC.ai[3]=0;Main.player[0].velocity=new(badVelocity,0);int before=Projectile.Shots.Count;womb.ReleaseCompressionField(Main.player[0],18);Check(float.IsFinite(badVelocity)?Projectile.Shots.Count==before+1&&Projectile.Positions.Last()==Main.player[0].Center:Projectile.Shots.Count==before&&womb.NPC.ai[3]==0,"Compression rejects invalid target velocity and bounds finite prediction overflow");}
}
foreach(int reason in Enumerable.Range(0,5)){Setup();Projectile.Shots.Clear();var deniedWomb=new AbyssalStarWomb{NPC=Main.npc[0]};var aim=Main.player[0];if(reason==0)Main.netMode=1;else if(reason==1)deniedWomb.NPC.active=false;else if(reason==2)Main.player[0].dead=true;else if(reason==3)aim=new();else deniedWomb.NPC.target=255;deniedWomb.ReleaseCompressionField(aim,18);Check(Projectile.Shots.Count==0&&deniedWomb.NPC.ai[3]==0,"Compression invalid battle/client cannot release or advance cadence");}
foreach(int mode in new[]{0,2})foreach(int spokes in new[]{6,8,12}) {
 Setup();Main.netMode=mode;Projectile.Shots.Clear();var star=new AbyssalStarWomb{NPC=Main.npc[0]};int interval=spokes==12?180:spokes==8?240:300;star.NPC.ai[2]=interval-60;int hitSlot=0;float starAim=0;
 for(int warning=1;warning<=60;warning++){star.UpdateStarRing(Main.player[0],spokes>=8,spokes==12);if(warning==1){starAim=star.NPC.ai[3];Main.player[0].Center=new(0,100);}Check(Projectile.Shots.Count(s=>s.Type==1)==(warning==60?spokes-2:0),"Star ring waits full warning then leaves two openings");Check(!star.CanHitPlayer(Main.player[0],ref hitSlot)&&star.NPC.ai[3]==starAim,"Star warning and release lock safe direction without contact");}
 Check(Projectile.Shots.Where(s=>s.Type==1).All(s=>Math.Abs(s.Velocity.Y)>0.001f),"Star ring omits locked and opposite spokes");Check(Projectile.Shots.Count(s=>s.Type==2)==(spokes>=8?1:0),"First eligible star ring releases one compression field");
 for(int recovery=1;recovery<=45;recovery++){star.UpdateStarRing(Main.player[0],spokes>=8,spokes==12);Check(!star.CanHitPlayer(Main.player[0],ref hitSlot),"Star entire recovery denies contact including last frame");}
 star.UpdateStarRing(Main.player[0],spokes>=8,spokes==12);Check(star.CanHitPlayer(Main.player[0],ref hitSlot),"Star normal contact returns after recovery");
}
foreach(int mode in new[]{0,2})foreach(bool recovery in new[]{false,true})foreach(bool replace in new[]{false,true}) {
 Setup();Main.netMode=mode;Projectile.Shots.Clear();var changedStar=new AbyssalStarWomb{NPC=Main.npc[0]};changedStar.NPC.ai[2]=240;changedStar.UpdateStarRing(Main.player[0],false,false);if(recovery)for(int warning=1;warning<60;warning++)changedStar.UpdateStarRing(Main.player[0],false,false);int count=Projectile.Shots.Count;if(replace)Main.player[0]=new(){Center=new(0,100)};else changedStar.NPC.target=1;
 Check(changedStar.UpdateStarRing(Main.player[changedStar.NPC.target],false,false)&&changedStar.NPC.ai.All(v=>v==0)&&changedStar.NPC.velocity==Vector2.Zero,"Star target replacement cancels warning or recovery");Check(Projectile.Shots.Count==count&&changedStar.NPC.netUpdate,"Star cancellation adds no attack and synchronizes");for(int idle=0;idle<240;idle++)Check(!changedStar.UpdateStarRing(Main.player[changedStar.NPC.target],false,false),"Star cancellation restores complete normal interval");changedStar.UpdateStarRing(Main.player[changedStar.NPC.target],false,false);Check(changedStar.NPC.ai[1]==59,"Star new target receives complete warning");
}
Setup();Projectile.Shots.Clear();var clientStar=new AbyssalStarWomb{NPC=Main.npc[0]};clientStar.NPC.ai[1]=30;Main.netMode=1;clientStar.UpdateStarRing(Main.player[0],false,false);Check(clientStar.NPC.ai[1]==30&&Projectile.Shots.Count==0,"Star client waits without advancing or firing");var starBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;clientStar.PreDraw(starBatch,default,default);Check(starBatch.Calls==0,"Star dedicated warning avoids graphics");Main.dedServ=false;clientStar.PreDraw(starBatch,default,default);Check(starBatch.Calls==4,"Star warning draws both edges for two openings");
Setup();var changingPhase=new AbyssalStarWomb{NPC=Main.npc[0]};Projectile.Shots.Clear();changingPhase.NPC.ai[2]=240;changingPhase.UpdateStarRing(Main.player[0],false,false);for(int warning=1;warning<59;warning++)changingPhase.UpdateStarRing(Main.player[0],true,true);Check(Projectile.Shots.Count==0,"Star phase change cannot shorten existing warning");changingPhase.UpdateStarRing(Main.player[0],true,true);Check(Projectile.Shots.Count(s=>s.Type==1)==10,"Star phase change releases final pattern only after full warning");
foreach(int mode in new[]{0,2}) {
 Setup();Main.netMode=mode;var sword=new FormlessSwordSoul{NPC=Main.npc[0]};sword.NPC.target=1;sword.SpawnSwordAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==3&&NPC.Calls==3,"Sword creates exactly three successful followers");Check(Main.ActiveNPCs.Where(n=>n.type==7).All(n=>n.target==1&&n.ai[0]==0&&n.netUpdate),"Sword followers inherit parent and synchronized target");for(int pattern=0;pattern<20;pattern++)sword.SpawnSwordAdds();Check(NPC.Calls==3,"Sword long battle does not exceed fixed creation quota");foreach(var add in Main.ActiveNPCs.Where(n=>n.type==7))add.active=false;sword.SpawnSwordAdds();Check(NPC.Calls==3,"Defeated sword followers never replenish quota");
 foreach(int capacity in new[]{0,1,2}){Setup();Main.netMode=mode;var partialSword=new FormlessSwordSoul{NPC=Main.npc[0]};foreach(var occupied in Main.npc.Skip(capacity+1)){occupied.active=true;occupied.type=8;}partialSword.SpawnSwordAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==capacity,"Sword partial capacity counts only created followers");foreach(var occupied in Main.npc.Where(n=>n.type==8))occupied.active=false;partialSword.SpawnSwordAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==3,"Sword next pattern fills only missing successful quota");int calls=NPC.Calls;partialSword.SpawnSwordAdds();Check(NPC.Calls==calls,"Sword completed partial quota prevents further attempts");}
 foreach(int bad in new[]{-1,0,Main.maxNPCs,int.MaxValue}){Setup();Main.netMode=mode;var failedSword=new FormlessSwordSoul{NPC=Main.npc[0]};NPC.FailureResult=bad;failedSword.SpawnSwordAdds();Check(NPC.Calls==1,"Sword failed creation stops current batch without indexing sentinel");NPC.FailureResult=int.MinValue;failedSword.SpawnSwordAdds();Check(NPC.Calls==4&&Main.ActiveNPCs.Count(n=>n.type==7)==3,"Sword failed attempt does not consume successful quota");}
 foreach(int badEntity in new[]{0,1,2,3}){Setup();Main.netMode=mode;var invalidSword=new FormlessSwordSoul{NPC=Main.npc[0]};Main.npc[1]=badEntity==0?null:new NPC{active=badEntity!=1,life=badEntity==2?0:100,type=badEntity==3?8:7};NPC.FailureResult=1;invalidSword.SpawnSwordAdds();Check(Main.npc[1]==null||!Main.npc[1].netUpdate,"Sword invalid returned entity receives no target or dirty state");Main.npc[1]=new NPC{whoAmI=1};NPC.FailureResult=int.MinValue;invalidSword.SpawnSwordAdds();Check(NPC.Calls==4&&Main.ActiveNPCs.Count(n=>n.type==7)==3,"Sword invalid returned entity leaves full quota missing");}
}
foreach(int invalid in Enumerable.Range(0,6)){Setup();var deniedSword=new FormlessSwordSoul{NPC=Main.npc[0]};if(invalid==0)Main.netMode=1;else if(invalid==1)deniedSword.NPC.active=false;else if(invalid==2)Main.player[0].dead=true;else if(invalid==3)deniedSword.NPC.target=255;else if(invalid==4)deniedSword.NPC.life=0;else Main.player[0].Center=new(5000,0);deniedSword.SpawnSwordAdds();Check(NPC.Calls==0,"Sword invalid battle/client cannot attempt followers");}
foreach(int mode in new[]{0,2})foreach(int rows in new[]{1,2,3}) {
 Setup();Main.netMode=mode;var lanes=new FormlessSwordSoul{NPC=Main.npc[0]};int interval=rows==3?180:rows==2?240:300;int contactSlot=0;
 for(int orientation=0;orientation<2;orientation++) {
  Projectile.Shots.Clear();Projectile.Positions.Clear();lanes.NPC.ai[2]=interval-45;Main.player[0].Center=new(100,100);
  for(int warning=1;warning<=45;warning++){lanes.UpdateSwordLanes(Main.player[0],rows>=2,rows==3);if(warning==1)Main.player[0].Center=new(200,200);Check(Projectile.Shots.Count==(warning==45?rows*4:0),"Sword lanes wait full warning before symmetric rows release");Check(!lanes.CanHitPlayer(Main.player[0],ref contactSlot),"Sword warning and release refuse contact");Check(lanes.NPC.ai[0]==100&&lanes.NPC.ai[3]==100,"Sword warning locks center despite target movement");}
  Check(Projectile.Shots.All(s=>orientation==0?s.Velocity.Y==0:s.Velocity.X==0),"Sword alternates horizontal and vertical rows");
  Check(Projectile.Positions.All(p=>orientation==0?Math.Abs(p.Y-100)>=112&&Math.Abs(p.X-100)==320:Math.Abs(p.X-100)>=112&&Math.Abs(p.Y-100)==320),"Sword central safe corridor remains clear of spawn rows");
  for(int recovery=1;recovery<=45;recovery++){lanes.UpdateSwordLanes(Main.player[0],rows>=2,rows==3);Check(!lanes.CanHitPlayer(Main.player[0],ref contactSlot),"Sword full recovery includes harmless final frame");}
  lanes.UpdateSwordLanes(Main.player[0],rows>=2,rows==3);Check(lanes.CanHitPlayer(Main.player[0],ref contactSlot),"Sword normal contact resumes after full recovery");
 }
 Check(NPC.Calls==(rows>=2?3:0),"Sword successive arrays retain fixed follower success quota");
}
foreach(int mode in new[]{0,2})foreach(bool recovery in new[]{false,true})foreach(bool replace in new[]{false,true}) {
 Setup();Main.netMode=mode;Projectile.Shots.Clear();var switchedLanes=new FormlessSwordSoul{NPC=Main.npc[0]};switchedLanes.NPC.ai[2]=255;switchedLanes.UpdateSwordLanes(Main.player[0],false,false);if(recovery)for(int warning=1;warning<45;warning++)switchedLanes.UpdateSwordLanes(Main.player[0],false,false);int shots=Projectile.Shots.Count;if(replace)Main.player[0]=new();else switchedLanes.NPC.target=1;
 Check(switchedLanes.UpdateSwordLanes(Main.player[switchedLanes.NPC.target],false,false)&&switchedLanes.NPC.ai.All(v=>v==0)&&switchedLanes.NPC.velocity==Vector2.Zero,"Sword retarget cancels locked array and recovery");Check(Projectile.Shots.Count==shots&&switchedLanes.NPC.netUpdate,"Sword cancellation does not append attacks");
 for(int idle=0;idle<255;idle++)Check(!switchedLanes.UpdateSwordLanes(Main.player[switchedLanes.NPC.target],false,false),"Sword new target gets complete interval");
}
foreach(int mode in new[]{0,1,2})foreach(float bad in new[]{float.NaN,float.PositiveInfinity,-46f,46f,0.5f}){Setup();Main.netMode=mode;var badLanes=new FormlessSwordSoul{NPC=Main.npc[0]};badLanes.NPC.ai[1]=bad;int invalidLaneSlot=0;Check(badLanes.UpdateSwordLanes(Main.player[0],false,false)&&!badLanes.CanHitPlayer(Main.player[0],ref invalidLaneSlot),"Sword malformed countdown harmless");Check(mode==1||badLanes.NPC.ai.All(v=>v==0),"Sword authority repairs invalid countdown");}
Setup();Projectile.Shots.Clear();var laneClient=new FormlessSwordSoul{NPC=Main.npc[0]};laneClient.NPC.ai[1]=-20;Main.netMode=1;laneClient.UpdateSwordLanes(Main.player[0],false,false);Check(laneClient.NPC.ai[1]==-20&&Projectile.Shots.Count==0,"Sword client keeps signed vertical countdown and never fires");var laneBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;laneClient.PreDraw(laneBatch,default,default);Check(laneBatch.Calls==0,"Sword dedicated preview skips rendering");Main.dedServ=false;laneClient.PreDraw(laneBatch,default,default);Check(laneBatch.Calls==4,"Sword preview draws safe edges and dangerous row paths");
foreach(int mode in new[]{0,2}) {
 Setup();Main.netMode=mode;var medicine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};medicine.NPC.lifeMax=10000;medicine.NPC.life=5000;int hitSlot=0;
 for(int healing=0;healing<3;healing++) {
  medicine.NPC.ai[1]=239;int before=medicine.NPC.life;
  for(int frame=1;frame<=90;frame++){medicine.UpdateMedicineRitual(Main.player[0],true);Check(medicine.NPC.life==before+(frame==90?100:0),"Medicine heals only at complete ninety frame boundary");Check(!medicine.CanHitPlayer(Main.player[0],ref hitSlot),"Medicine reading and release refuse contact");}
  for(int recovery=1;recovery<=60;recovery++){medicine.UpdateMedicineRitual(Main.player[0],true);Check(!medicine.CanHitPlayer(Main.player[0],ref hitSlot),"Medicine full sixty frame recovery remains harmless");}
  Check(medicine.NPC.ai[1]==0,"Medicine completes recovery and resets cooldown");
 }
 for(int idle=0;idle<300;idle++)Check(!medicine.UpdateMedicineRitual(Main.player[0],true),"Medicine three successful heals exhaust encounter quota");Check(medicine.NPC.life==5300,"Medicine total healing bounded to three percent");
 foreach(int damage in new[]{99,100,101}) {
  Setup();Main.netMode=mode;var interruptedMedicine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};interruptedMedicine.NPC.lifeMax=10000;interruptedMedicine.NPC.life=5000;interruptedMedicine.NPC.ai[1]=239;interruptedMedicine.UpdateMedicineRitual(Main.player[0],true);interruptedMedicine.NPC.life-=damage;interruptedMedicine.UpdateMedicineRitual(Main.player[0],true);Check((interruptedMedicine.NPC.ai[1]==-91)==(damage>=100),"Medicine interrupt threshold includes exact one percent damage");if(damage>=100){int life=interruptedMedicine.NPC.life;for(int recover=0;recover<60;recover++)interruptedMedicine.UpdateMedicineRitual(Main.player[0],true);Check(interruptedMedicine.NPC.life==life,"Interrupted medicine ritual never heals");}
 }
 Setup();Main.netMode=mode;var cappedMedicine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};cappedMedicine.NPC.lifeMax=10000;cappedMedicine.NPC.life=9999;cappedMedicine.NPC.ai[1]=239;for(int frame=0;frame<90;frame++)cappedMedicine.UpdateMedicineRitual(Main.player[0],true);Check(cappedMedicine.NPC.life==10000,"Medicine never heals above maximum life");
}
Setup();var medicineClient=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};medicineClient.NPC.ai[1]=-20;Main.netMode=1;int clientLife=medicineClient.NPC.life;medicineClient.UpdateMedicineRitual(Main.player[0],true);Check(medicineClient.NPC.ai[1]==-20&&medicineClient.NPC.life==clientLife,"Medicine client cannot advance reading or heal");var medicineBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;medicineClient.PreDraw(medicineBatch,default,default);Check(medicineBatch.Calls==0,"Medicine dedicated server skips progress drawing");Main.dedServ=false;medicineClient.PreDraw(medicineBatch,default,default);Check(medicineBatch.Calls==2,"Medicine reading has visible progress track and fill");
foreach(int mode in new[]{0,2})foreach(bool replaceOwner in new[]{false,true}){Setup();Main.netMode=mode;var changedMedicine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};changedMedicine.NPC.lifeMax=10000;changedMedicine.NPC.life=5000;changedMedicine.NPC.ai[1]=239;changedMedicine.UpdateMedicineRitual(Main.player[0],true);if(replaceOwner)Main.player[0]=new();else changedMedicine.NPC.target=1;changedMedicine.UpdateMedicineRitual(Main.player[changedMedicine.NPC.target],true);Check(changedMedicine.NPC.ai[1]==-91&&changedMedicine.NPC.life==5000&&changedMedicine.NPC.netUpdate,"Medicine target replacement interrupts without healing");}
foreach(int mode in new[]{0,1,2})foreach(float badRitual in new[]{float.NaN,float.PositiveInfinity,-151f,241f,0.5f}){Setup();Main.netMode=mode;var brokenMedicine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};brokenMedicine.NPC.ai[1]=badRitual;int ritualHitSlot=0;Check(brokenMedicine.UpdateMedicineRitual(Main.player[0],true)&&!brokenMedicine.CanHitPlayer(Main.player[0],ref ritualHitSlot),"Medicine malformed ritual state cannot heal or contact");Check(mode==1||brokenMedicine.NPC.ai[1]==0&&brokenMedicine.NPC.netUpdate,"Medicine authority repairs malformed ritual state");}
void VineArena(){Setup();Main.npc[0].Center=new(1000,1000);foreach(var player in Main.player)player.Center=new(1100,1000);}
foreach(int mode in new[]{0,2}) {
 VineArena();Main.netMode=mode;var vine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};vine.NPC.target=1;vine.SpawnVineAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==3&&NPC.Calls==3,"Vine creates exactly three successful followers");Check(Main.ActiveNPCs.Where(n=>n.type==7).All(n=>n.target==1&&n.ai[0]==0&&n.netUpdate),"Vine followers inherit parent and synchronized target");for(int pattern=0;pattern<20;pattern++)vine.SpawnVineAdds();Check(NPC.Calls==3,"Vine long battle does not exceed fixed creation quota");foreach(var add in Main.ActiveNPCs.Where(n=>n.type==7))add.active=false;vine.SpawnVineAdds();Check(NPC.Calls==3,"Defeated vine followers never replenish quota");
 foreach(int capacity in new[]{0,1,2}){VineArena();Main.netMode=mode;var partialVine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};foreach(var occupied in Main.npc.Skip(capacity+1)){occupied.active=true;occupied.type=8;}partialVine.SpawnVineAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==capacity,"Vine partial capacity counts only created followers");foreach(var occupied in Main.npc.Where(n=>n.type==8))occupied.active=false;partialVine.SpawnVineAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==3,"Vine next pattern fills only missing successful quota");int calls=NPC.Calls;partialVine.SpawnVineAdds();Check(NPC.Calls==calls,"Vine completed partial quota prevents further attempts");}
 foreach(int bad in new[]{-1,0,Main.maxNPCs,int.MaxValue}){VineArena();Main.netMode=mode;var failedVine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};NPC.FailureResult=bad;failedVine.SpawnVineAdds();Check(NPC.Calls==1,"Vine failed creation stops current batch without indexing sentinel");NPC.FailureResult=int.MinValue;failedVine.SpawnVineAdds();Check(NPC.Calls==4&&Main.ActiveNPCs.Count(n=>n.type==7)==3,"Vine failed attempt does not consume successful quota");}
 foreach(int badEntity in new[]{0,1,2,3}){VineArena();Main.netMode=mode;var invalidVine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};Main.npc[1]=badEntity==0?null:new NPC{active=badEntity!=1,life=badEntity==2?0:100,type=badEntity==3?8:7};NPC.FailureResult=1;invalidVine.SpawnVineAdds();Check(Main.npc[1]==null||!Main.npc[1].netUpdate,"Vine invalid returned entity receives no target or dirty state");Main.npc[1]=new NPC{whoAmI=1};NPC.FailureResult=int.MinValue;invalidVine.SpawnVineAdds();Check(NPC.Calls==4&&Main.ActiveNPCs.Count(n=>n.type==7)==3,"Vine invalid returned entity leaves full quota missing");}
}
foreach(int invalid in Enumerable.Range(0,6)){VineArena();var deniedVine=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};if(invalid==0)Main.netMode=1;else if(invalid==1)deniedVine.NPC.active=false;else if(invalid==2)Main.player[0].dead=true;else if(invalid==3)deniedVine.NPC.target=255;else if(invalid==4)deniedVine.NPC.life=0;else Main.player[0].Center=new(5000,0);deniedVine.SpawnVineAdds();Check(NPC.Calls==0,"Vine invalid battle/client cannot attempt followers");}
foreach(int mode in new[]{0,2}) {
 Setup();Main.netMode=mode;var preparedVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};preparedVines.NPC.Center=new(1000,1000);Main.player[0].Center=new(1500,1100);preparedVines.NPC.velocity=new(4,5);int vineSlot=0;
 for(int warning=1;warning<=45;warning++){if(warning==1)Check(preparedVines.BeginVineSummon(Main.player[0]),"Medicine summon begins synchronized warning");else preparedVines.UpdateVineSummon(Main.player[0]);Check(NPC.Calls==(warning==45?3:0),"Vines create only at full forty-five frame boundary");Check(preparedVines.NPC.velocity==Vector2.Zero&&!preparedVines.CanHitPlayer(Main.player[0],ref vineSlot),"Medicine summon warning freezes caster and contact");}
 Check(Main.ActiveNPCs.Where(n=>n.type==7).All(n=>Math.Abs(n.Center.X-1000)<=120&&n.Center.Y==940),"Vines spawn in advertised boss-side area instead of target location");
 for(int recovery=1;recovery<=30;recovery++){preparedVines.UpdateVineSummon(Main.player[0]);Check(!preparedVines.CanHitPlayer(Main.player[0],ref vineSlot),"Medicine complete summon recovery remains harmless");}
 Check(!preparedVines.UpdateVineSummon(Main.player[0])&&preparedVines.CanHitPlayer(Main.player[0],ref vineSlot),"Medicine normal contact returns after summon recovery");Check(!preparedVines.BeginVineSummon(Main.player[0])&&NPC.Calls==3,"Completed vine quota prevents further summon rituals");
 foreach(bool replaceVineTarget in new[]{false,true}){Setup();Main.netMode=mode;var cancelledVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};cancelledVines.BeginVineSummon(Main.player[0]);if(replaceVineTarget)Main.player[0]=new();else cancelledVines.NPC.target=1;cancelledVines.UpdateVineSummon(Main.player[cancelledVines.NPC.target]);Check(NPC.Calls==0&&cancelledVines.NPC.ai[3]==-30&&cancelledVines.NPC.netUpdate,"Target replacement cancels summon without consuming quota");for(int recovery=0;recovery<30;recovery++)cancelledVines.UpdateVineSummon(Main.player[cancelledVines.NPC.target]);Check(cancelledVines.BeginVineSummon(Main.player[cancelledVines.NPC.target]),"Cancelled summon permits full new warning after recovery");}
}
foreach(int mode in new[]{0,1,2})foreach(float badSummon in new[]{float.NaN,float.PositiveInfinity,-31f,46f,0.5f}){Setup();Main.netMode=mode;var badVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};badVines.NPC.ai[3]=badSummon;int badVineSlot=0;Check(badVines.UpdateVineSummon(Main.player[0])&&NPC.Calls==0&&!badVines.CanHitPlayer(Main.player[0],ref badVineSlot),"Bad vine summon clock harmless and creates nothing");Check(mode==1||badVines.NPC.ai[3]==-30,"Authority recovers bad summon clock");}
Setup();var remoteVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};remoteVines.NPC.ai[3]=20;Main.netMode=1;remoteVines.UpdateVineSummon(Main.player[0]);Check(remoteVines.NPC.ai[3]==20&&NPC.Calls==0,"Vine summon client never advances clock or creates NPC");var vineBatch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();Main.dedServ=true;remoteVines.PreDraw(vineBatch,default,default);Check(vineBatch.Calls==0,"Vine summon dedicated server skips preview");Main.dedServ=false;remoteVines.PreDraw(vineBatch,default,default);Check(vineBatch.Calls==4,"Vine summon preview outlines four spawn-area edges");
foreach(bool lavaSite in new[]{false,true}) {
 VineArena();var terrainVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};Collision.SpawnBlocked=!lavaSite;Collision.SpawnLava=lavaSite;Collision.SolidCalls=Collision.LavaCalls=0;
 terrainVines.SpawnVineAdds();Check(NPC.Calls==0&&Main.rand.Calls==12&&Collision.SolidCalls==12,"Blocked vine body searches at most twelve candidates without creating NPC");Check(Collision.LavaCalls==(lavaSite?12:0),"Vine lava test follows solid-body rejection");Collision.SpawnBlocked=Collision.SpawnLava=false;terrainVines.SpawnVineAdds();Check(NPC.Calls==3,"Terrain failure preserves all successful quota for later retry");Check(Collision.LastBody==new Vector2(976,892)&&Collision.LastWidth==48&&Collision.LastHeight==48,"Vine validates native center/bottom spawn body rather than only a point");
}
VineArena();var searchingVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};Collision.BlockedSamples=2;Collision.SolidCalls=0;Check(searchingVines.TryVineSpawnPosition(out int searchedX,out int searchedY)&&Main.rand.Calls==3&&searchedX==1000&&searchedY==940,"Vine skips obstructed samples and accepts next safe candidate");Collision.BlockedSamples=0;
foreach((float x,float y,bool accepted) in new[]{(40f,124f,true),(39f,124f,false),(40f,123f,false),(134360f,38444f,true),(134361f,38444f,false),(40f,38445f,false)}) {
 VineArena();var edgeVines=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};edgeVines.NPC.Center=new(x,y);Collision.SolidCalls=0;bool found=edgeVines.TryVineSpawnPosition(out int edgeX,out int edgeY);Check(found==accepted,"Vine full body world margin includes exact safe boundary");Check(accepted||Collision.SolidCalls==0&&edgeX==0&&edgeY==0,"Outside vine body never accesses terrain or returns a spawn point");
}
VineArena();var sampledEdge=new GreenwoodMedicineKingEcho{NPC=Main.npc[0]};sampledEdge.NPC.Center=new(30,1000);Main.rand.Values.Enqueue(-120);Main.rand.Values.Enqueue(20);Check(sampledEdge.TryVineSpawnPosition(out int sampledX,out int sampledY)&&sampledX==50&&Main.rand.Calls==2,"Vine edge search finds safe sample inside advertised range");
Console.WriteLine($"Actual furnace shard spawn hook passed: {checks} checks; native creation/target/network boundaries mocked.");
