using Microsoft.Xna.Framework;using Terraria;using Terraria.ID;using XianXia.Content.NPCs.Bosses;
int checks=0;void Check(bool value,string message){checks++;if(!value)throw new Exception(message);}
BlackFurnaceIronGolem Setup(int count=0){Main.netMode=NetmodeID.Server;Main.player=[new(){Center=new(100,0)},new(){Center=new(200,0)}];Main.npc=Enumerable.Range(0,Main.maxNPCs).Select(i=>new NPC{whoAmI=i}).ToArray();Main.rand=new();NPC.Calls=0;NPC.FailureResult=int.MinValue;var boss=new BlackFurnaceIronGolem();boss.NPC=Main.npc[0];boss.NPC.active=true;boss.NPC.type=9;for(int index=1;index<=count;index++){Main.npc[index].active=true;Main.npc[index].type=7;}return boss;}
foreach(int initial in new[]{0,1,2,3,4,5,6,7,10}){var boss=Setup(initial);boss.SpawnShardAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)==initial+Math.Max(0,Math.Min(2,6-initial)),"Per-pattern batch respects nearby cap");Check(NPC.Calls==Math.Max(0,Math.Min(2,6-initial)),"Cap prevents even attempted spawn");foreach(var created in Main.ActiveNPCs.Where(n=>n.type==7&&n.netUpdate))Check(created.target==boss.NPC.target&&created.ai[0]==0,"New shard retains parent slot and target and is synchronized");}
var repeated=Setup();for(int wave=0;wave<100;wave++){repeated.SpawnShardAdds();Check(Main.ActiveNPCs.Count(n=>n.type==7)<=6,"Long fight never exceeds six nearby shards");}Check(NPC.Calls==6,"Repeated full waves do not call spawner");Main.npc[1].active=false;Main.npc[2].active=false;repeated.SpawnShardAdds();Check(NPC.Calls==8&&Main.ActiveNPCs.Count(n=>n.type==7)==6,"Dead shard slots permit bounded replenishment");
foreach(float distance in new[]{1599f,1600f,1601f}){var boss=Setup(6);Main.npc[6].Center=new(distance,0);boss.SpawnShardAdds();Check(NPC.Calls==(distance<=1600?0:1),"Exact arena boundary counts natural shards");}
var unrelated=Setup(6);foreach(var npc in Main.npc.Skip(1).Take(6))npc.type=8;unrelated.SpawnShardAdds();Check(NPC.Calls==2,"Other enemy types do not fill shard cap");
var expired=Setup(6);Main.npc[1].life=0;expired.SpawnShardAdds();Check(NPC.Calls==1,"Active zero-life shard does not consume combat quota");
foreach(int failure in new[]{-1,Main.maxNPCs,int.MaxValue}){var boss=Setup();NPC.FailureResult=failure;boss.SpawnShardAdds();Check(NPC.Calls==1&&Main.ActiveNPCs.Count()==1,"Failed creation stops batch without indexing sentinel");}
var full=Setup();foreach(var npc in Main.npc.Skip(1)){npc.active=true;npc.type=8;}full.SpawnShardAdds();Check(NPC.Calls==1,"Full NPC table stops safely");
var wrong=Setup();Main.npc[1].active=true;Main.npc[1].type=8;NPC.FailureResult=1;wrong.SpawnShardAdds();Check(NPC.Calls==1&&!Main.npc[1].netUpdate,"Returned unrelated NPC cannot receive shard synchronization");
foreach(Action<BlackFurnaceIronGolem> invalidate in new Action<BlackFurnaceIronGolem>[] {b=>Main.netMode=NetmodeID.MultiplayerClient,b=>b.NPC.active=false,b=>b.NPC.life=0,b=>b.NPC.target=-1,b=>Main.player[0].dead=true,b=>Main.player[0].active=false,b=>Main.player[0].Center=new(5000,0),b=>b.NPC.Center=new(float.NaN,0)}){var boss=Setup();invalidate(boss);boss.SpawnShardAdds();Check(NPC.Calls==0&&Main.rand.Calls==0,"Invalid battle/client produces no summons or spawn RNG");}
var charging=Setup();charging.NPC.ai[1]=179;Check(charging.UpdateFurnaceCharge(Main.player[0],true)&&charging.NPC.netUpdate,"furnace begins synchronized charge warning");float locked=charging.NPC.ai[3];Main.player[0].Center=new(0,100);for(int tick=1;tick<40;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.ai[3]==locked&&charging.NPC.velocity.X==0,"warning locks aim and avoids rushing");charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.velocity.X==14&&charging.NPC.velocity.Y==0,"dash follows locked direction despite player movement");for(int tick=1;tick<24;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.velocity.X<14,"dash enters recovery after twenty-four ticks");for(int tick=1;tick<40;tick++)charging.UpdateFurnaceCharge(Main.player[0],true);Check(charging.NPC.ai[1]==0&&charging.NPC.ai[0]==0&&charging.NPC.ai[2]==0,"recovery resets attack cooldowns");var clientCharge=Setup();Main.netMode=1;clientCharge.NPC.ai[1]=179;Check(!clientCharge.UpdateFurnaceCharge(Main.player[0],true)&&clientCharge.NPC.ai[1]==179,"client cannot begin charge");clientCharge.NPC.ai[1]=-41;Check(clientCharge.UpdateFurnaceCharge(Main.player[0],true)&&clientCharge.NPC.ai[1]==-41,"client follows synchronized phase without advancing it");
Console.WriteLine($"Actual furnace shard spawn hook passed: {checks} checks; native creation/target/network boundaries mocked.");
