namespace Microsoft.Xna.Framework { public record struct Vector2(float X,float Y) {public static Vector2 Zero=>new(0,0);public static Vector2 UnitY=>new(0,1);public Vector2 SafeNormalize(Vector2 fallback){float length=Length();return length>0?this/length:fallback;}public Vector2 RotatedBy(float a)=>new(X*MathF.Cos(a)-Y*MathF.Sin(a),X*MathF.Sin(a)+Y*MathF.Cos(a));public static Vector2 Lerp(Vector2 a,Vector2 b,float amount)=>a+(b-a)*amount;public static Vector2 operator +(Vector2 a,Vector2 b)=>new(a.X+b.X,a.Y+b.Y);public static float DistanceSquared(Vector2 a,Vector2 b){var d=a-b;return d.X*d.X+d.Y*d.Y;}public float Length()=>MathF.Sqrt(X*X+Y*Y);public float ToRotation()=>MathF.Atan2(Y,X);public static Vector2 operator -(Vector2 a,Vector2 b)=>new(a.X-b.X,a.Y-b.Y);public static Vector2 operator /(Vector2 a,float b)=>new(a.X/b,a.Y/b);public static Vector2 operator *(Vector2 a,float b)=>new(a.X*b,a.Y*b);} }
namespace Terraria { public class NPC {public bool active;public Terraria.ModLoader.ModNPC ModNPC;public int width,height,aiStyle;public float knockBackResist;public bool noGravity,noTileCollide;public object HitSound,DeathSound;public float[] localAI=new float[4];public int type,whoAmI,realLife=-1,life,lifeMax,damage,defense,timeLeft,target;public bool netUpdate;public float[] ai=new float[4];public float rotation;public Microsoft.Xna.Framework.Vector2 Center,velocity;public object GetSource_FromAI()=>new Terraria.DataStructures.EntitySource_Parent(this);public static int Calls,FailAt;public static int NewNPC(object source,int x,int y,int type,float ai0,float ai1,float ai2){Calls++;if(Calls==FailAt)return Main.maxNPCs;for(int i=0;i<Main.maxNPCs;i++)if(!Main.npc[i].active){var n=new NPC{whoAmI=i,active=true,type=type,life=70,lifeMax=70};Main.npc[i]=n;n.ModNPC=type==9?new XianXia.Content.NPCs.Bosses.ShatteredJadeWyrmMinionBody():new XianXia.Content.NPCs.Bosses.ShatteredJadeWyrmMinionTail();n.ModNPC.NPC=n;n.ai[0]=ai0;n.ai[1]=ai1;n.ai[2]=ai2;return i;}return Main.maxNPCs;}} public static class Main {public static int maxNPCs=20,netMode,maxPlayers=2;public static Player[] player=[new(),new()];public static bool dedServ;public static int[] npcFrameCount=new int[100];public static NPC[] npc=Array.Empty<NPC>();} public static class Lighting {public static int Calls;public static void AddLight(Microsoft.Xna.Framework.Vector2 p,float r,float g,float b)=>Calls++;} public static class NetMessage {public static int Calls;public static void SendData(int id,int number)=>Calls++;} }
namespace Terraria.ID {public static class NetmodeID {public const int MultiplayerClient=1,Server=2;}public static class MessageID {public const int SyncNPC=23;}}

namespace Terraria {public class Player{public bool active=true,dead;public Microsoft.Xna.Framework.Vector2 Center,velocity;}}

namespace Microsoft.Xna.Framework{public static class MathHelper{public const float PiOver2=MathF.PI/2;}}
namespace Terraria.ID{public static class SoundID{public static object NPCHit1=new(),NPCDeath1=new();}}
namespace Terraria.DataStructures{public interface IEntitySource{}public class EntitySource_Parent(object entity):IEntitySource{public object Entity=entity;}public class NaturalSource:IEntitySource{}}
namespace Terraria.ModLoader{public class ModNPC{public Terraria.NPC NPC=new();public int Type;public virtual void SetStaticDefaults(){}public virtual void SetDefaults(){}public virtual void SetBestiary(Terraria.GameContent.Bestiary.BestiaryDatabase database,Terraria.GameContent.Bestiary.BestiaryEntry entry){}public virtual bool CheckActive()=>true;public virtual void AI(){}public virtual void OnSpawn(Terraria.DataStructures.IEntitySource source){}public virtual bool PreAI()=>true;public virtual bool CanHitPlayer(Terraria.Player target,ref int cooldownSlot)=>true;public virtual bool CanHitNPC(Terraria.NPC target)=>true;public virtual void SendExtraAI(System.IO.BinaryWriter writer){}public virtual void ReceiveExtraAI(System.IO.BinaryReader reader){}}public static class ModContent{public static int NPCType<T>()=>typeof(T).Name switch{"SpiritVeinWyrm"=>7,"ShatteredJadeWyrmMinion"=>8,"ShatteredJadeWyrmMinionBody"=>9,_=>10};}}
namespace Terraria.GameContent.Bestiary{public class BestiaryDatabase{}public class BestiaryEntry{public List<object> Info=new();}public class FlavorTextBestiaryInfoElement(string text){public string Text=text;}}
namespace XianXia.Content.NPCs.Bosses{public partial class SpiritVeinWyrm:XianXia.Common.NPCs.LinkedWormNPC{internal override bool IsWormHead=>true;}}
