<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../../Common/Systems/CultivationFishingRules.cs" Link="Rules.cs"/><Compile Include="../../../Common/Players/CultivationFishingPlayer.cs" Link="Player.cs"/><Compile Include="../../../Common/Items/CultivationFishingCrate.cs" Link="Crate.cs"/><Compile Include="../../../Content/Items/Fishing/CultivationCrates.cs" Link="Crates.cs"/></ItemGroup></Project>