using Terraria;using Terraria.ID;using XianXia.Content.NPCs.Bosses;
int assertions=0;void Check(bool ok,string msg){assertions++;if(!ok)throw new Exception(msg);}NPC Setup(){Main.player=[new Player(),new Player()];Main.npc=Enumerable.Range(0,Main.maxNPCs).Select(i=>new NPC{whoAmI=i}).ToArray();Main.netMode=NetmodeID.Server;Main.dedServ=true;NPC.Calls=0;NPC.FailAt=0;NetMessage.Calls=0;Lighting.Calls=0;var h=Main.npc[0];h.active=true;h.type=10;h.life=60;h.lifeMax=100;h.damage=20;h.defense=8;return h;}
var head=Setup();Check(SegmentedWormAI.TrySpawnChain(head,11,12,3),"Complete chain spawns");Check(Main.npc.Count(n=>n.active)==5&&Main.npc[4].type==12,"Body count and tail");var body=Main.npc[2];SegmentedWormAI.FollowPreviousSegment(body,16,.1f,.1f,.1f,10);Check(body.life==60&&body.lifeMax==100&&body.damage==20&&body.defense==8&&body.realLife==0,"Segments inherit actual head state");Check(Lighting.Calls==0,"No dedicated lighting");head.active=false;SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(!body.active&&NetMessage.Calls==1,"Server cleans missing head and synchronizes");
head=Setup();NPC.FailAt=3;Check(!SegmentedWormAI.TrySpawnChain(head,11,12,3),"Mid-chain failure returns false");Check(Main.npc.Count(n=>n.active)==1&&head.active&&NetMessage.Calls==2,"Rollback only created segments");
head=Setup();foreach(var n in Main.npc.Skip(1))n.active=true;Check(!SegmentedWormAI.TrySpawnChain(head,11,12,3)&&NPC.Calls==0,"Capacity preflight avoids partial chains");Check(SegmentedWormAI.SpawnSegment(head,0,11,1)==-1,"Sentinel does not index array");
head=Setup();Main.netMode=NetmodeID.MultiplayerClient;Check(!SegmentedWormAI.TrySpawnChain(head,11,12,3)&&NPC.Calls==0,"Client cannot generate segments");body=Main.npc[1];body.active=true;body.ai[0]=0;body.ai[1]=0;body.damage=20;head.active=false;SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(body.active&&body.damage==0&&NetMessage.Calls==0,"Out-of-order client data waits without damage or authoritative deletion");
head=Setup();Check(SegmentedWormAI.TrySpawnChain(head,11,12,1),"Small chain");head.type=99;body=Main.npc[1];SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(!body.active,"Reused head slot cannot attach to unrelated NPC");
head=Setup();SegmentedWormAI.TrySpawnChain(head,11,12,2);Main.npc[1].realLife=7;body=Main.npc[2];SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(!body.active,"Previous segment must belong to same head");

foreach(Action<NPC> invalidate in new Action<NPC>[] {n=>n.target=-1,n=>n.target=255,n=>n.life=0,n=>Main.player[0].dead=true,n=>Main.player[0].active=false,n=>Main.player[0].Center=new(5000,0),n=>Main.player[0].Center=new(float.NaN,0)}) {
 head=Setup();SegmentedWormAI.TrySpawnChain(head,11,12,1);body=Main.npc[1];invalidate(head);
 SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(body.damage==0,"Live head with invalid target cannot lend contact damage to body");
}
head=Setup();SegmentedWormAI.TrySpawnChain(head,11,12,1);body=Main.npc[1];Main.player[0].dead=true;SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Main.player[0].dead=false;SegmentedWormAI.FollowPreviousSegment(body,16,0,0,0,10);Check(body.damage==head.damage,"Valid returning head restores its current contact damage");
Console.WriteLine($"Actual segmented-worm source regression passed: {assertions} assertions; mocked spawn/network boundary.");
