using System.IO;
using Terraria;
using Terraria.ID;
using Terraria.DataStructures;
using XianXia.Content.NPCs.Bosses;
using XianXia.Content.NPCs.Enemies;

int checks=0;
void Check(bool ok,string name){checks++;if(!ok)throw new Exception(name);}
BlackFurnaceIronGolem Parent(){var boss=new BlackFurnaceIronGolem();boss.NPC=new(){active=true,life=100,whoAmI=3,target=0,ModNPC=boss};Main.npc[3]=boss.NPC;return boss;}
IronShardSpirit Child(BlackFurnaceIronGolem boss){var child=new IronShardSpirit();child.NPC=new(){active=true,life=70,whoAmI=4,ModNPC=child};child.OnSpawn(new EntitySource_Parent(boss.NPC));return child;}
byte[] Save(Terraria.ModLoader.ModNPC npc){using var stream=new MemoryStream();using var writer=new BinaryWriter(stream);npc.SendExtraAI(writer);return stream.ToArray();}
void Read(Terraria.ModLoader.ModNPC npc,byte[] data){using var stream=new MemoryStream(data);using var reader=new BinaryReader(stream);npc.ReceiveExtraAI(reader);}
bool Hit(IronShardSpirit child){int cooldown=0;return child.CanHitPlayer(Main.player[0],ref cooldown)&&child.CanHitNPC(new());}
void Reset(int mode=0){Main.netMode=mode;Main.npc=Enumerable.Range(0,Main.maxNPCs).Select(i=>new NPC{whoAmI=i}).ToArray();Main.player=[new(),new(){active=false}];NetMessage.Calls=0;}
Reset();var natural=new IronShardSpirit();natural.OnSpawn(new NaturalSource());Check(natural.PreAI()&&Hit(natural),"natural source unaffected");
var ordinary=new IronShardSpirit();ordinary.OnSpawn(new EntitySource_Parent(new NPC()));Check(ordinary.PreAI(),"ordinary parent unaffected");
for(int mode=0;mode<=2;mode++){
 for(int failure=0;failure<9;failure++){
  Reset();var boss=Parent();var child=Child(boss);Check(Hit(child),"live source hit");Main.netMode=mode;
  switch(failure){case 0:boss.NPC.active=false;break;case 1:boss.NPC.life=0;break;case 2:Main.player[0].dead=true;break;case 3:boss.NPC.target=255;break;case 4:child.NPC.Center=new(4001,0);break;case 5:child.NPC.velocity=new(float.NaN,0);break;case 6:Main.npc[3]=new(){active=true,life=100};break;case 7:Main.netMode=0;Parent();Main.netMode=mode;break;case 8:boss.NPC.Center=new(float.PositiveInfinity,0);break;}
  Check(!Hit(child)&&!child.PreAI(),"invalid source blocks AI and damage");
  Check(child.NPC.active==(mode==1),"only authority removes child");Check(NetMessage.Calls==(mode==2?1:0),"server sync once");
  child.PreAI();Check(NetMessage.Calls==(mode==2?1:0),"idempotent cleanup");
 }
}
Reset(2);var expiryBoss=Parent();var expiring=Child(expiryBoss);for(int tick=1;tick<900;tick++)Check(expiring.PreAI(),"alive before lifetime boundary");Check(!expiring.PreAI()&&!Hit(expiring)&&!expiring.NPC.active&&NetMessage.Calls==1,"expires at tick900");
Reset();var first=Parent();var firstSession=first.SummonSession;var second=Parent();Check(firstSession>0&&second.SummonSession!=firstSession,"slot replacement session unique");
var valid=Child(second);var wire=Save(valid);Check(wire.Length==13,"fixed child wire size");Check(Save(second).Length==8,"fixed boss wire size");
for(int length=0;length<13;length++){var copy=Child(second);var before=Save(copy);try{Read(copy,wire[..length]);throw new Exception("accepted truncated child");}catch(EndOfStreamException){}Check(Save(copy).SequenceEqual(before),"truncated packet atomic");}
for(int length=0;length<8;length++){var before=Save(second);try{Read(second,before[..length]);throw new Exception("accepted truncated boss");}catch(EndOfStreamException){}Check(Save(second).SequenceEqual(before),"truncated session atomic");}
Reset();var authority=Parent();var serverChild=Child(authority);var bossWire=Save(authority);var childWire=Save(serverChild);Main.netMode=1;var remote=new BlackFurnaceIronGolem();remote.NPC=authority.NPC;remote.NPC.ModNPC=remote;var remoteChild=new IronShardSpirit();remoteChild.NPC=new(){active=true,life=70};Read(remoteChild,childWire);
Check(!remoteChild.PreAI()&&!Hit(remoteChild)&&remoteChild.NPC.active,"child before parent packet waits harmlessly");Read(remote,bossWire);Check(remoteChild.PreAI()&&Hit(remoteChild),"parent packet restores client prediction");var age=Save(remoteChild);for(int i=0;i<1000;i++)remoteChild.PreAI();Check(Save(remoteChild).SequenceEqual(age),"client cannot expire authority child");
for(int slotIndex=0;slotIndex<3;slotIndex++)for(int sessionIndex=0;sessionIndex<3;sessionIndex++)for(int lifetimeIndex=0;lifetimeIndex<4;lifetimeIndex++){
 using var stream=new MemoryStream();using(var writer=new BinaryWriter(stream,System.Text.Encoding.UTF8,true)){writer.Write(true);writer.Write(new short[]{-1,3,short.MaxValue}[slotIndex]);writer.Write(new long[]{-1,0,authority.SummonSession}[sessionIndex]);writer.Write(new short[]{-1,0,900,short.MaxValue}[lifetimeIndex]);}
 Read(remoteChild,stream.ToArray());bool expected=slotIndex==1&&sessionIndex==2&&lifetimeIndex>=2;Check(Hit(remoteChild)==expected,"malformed binding remains harmless or clamped");
}
MoonboneImmortal MoonParent(){var boss=new MoonboneImmortal();boss.NPC=new(){active=true,life=100,whoAmI=3,target=0,ModNPC=boss};Main.npc[3]=boss.NPC;return boss;}
ArchivedImmortalSoul MoonChild(MoonboneImmortal boss){var child=new ArchivedImmortalSoul();child.NPC=new(){active=true,life=70,whoAmI=4,ModNPC=child};child.OnSpawn(new EntitySource_Parent(boss.NPC));return child;}
foreach(int mode in new[]{0,1,2})foreach(int reason in new[]{0,1,2,3,4,5}){Reset();var boss=MoonParent();var child=MoonChild(boss);Main.netMode=mode;if(reason==0)boss.NPC.active=false;else if(reason==1)Main.player[0].dead=true;else if(reason==2)boss.NPC.target=255;else if(reason==3)child.NPC.Center=new(4001,0);else if(reason==4)child.NPC.velocity=new(float.NaN,0);else{Main.netMode=0;MoonParent();Main.netMode=mode;}int cooldown=0;Check(!child.CanHitPlayer(Main.player[0],ref cooldown),"invalid moon source contact blocked");Check(!child.PreAI()&&child.NPC.velocity==Microsoft.Xna.Framework.Vector2.Zero,"invalid moon source freezes");Check(child.NPC.active==(mode==1),"only authority clears moon summons");Check(NetMessage.Calls==(mode==2?1:0),"moon cleanup dedicated broadcast");}
Reset();var moonOwner=MoonParent();var moonChild=MoonChild(moonOwner);for(int tick=0;tick<899;tick++)Check(moonChild.PreAI(),"moon summon lives before nine hundred ticks");Check(!moonChild.PreAI()&&!moonChild.NPC.active&&moonChild.NPC.damage==0,"moon expires without death rewards");Reset();moonOwner=MoonParent();moonChild=MoonChild(moonOwner);var moonWire=Save(moonChild);Check(moonWire.Length==13&&Save(moonOwner).Length==8,"moon source fixed wire layouts");for(int length=0;length<13;length++){try{Read(moonChild,moonWire[..length]);throw new Exception("truncated moon source accepted");}catch(EndOfStreamException){}Check(Save(moonChild).SequenceEqual(moonWire),"moon truncated source read atomic");}Main.netMode=1;for(int tick=0;tick<1000;tick++)moonChild.PreAI();Check(Save(moonChild).SequenceEqual(moonWire),"moon client never ages summon");Reset();var naturalMoon=new ArchivedImmortalSoul();naturalMoon.OnSpawn(new NaturalSource());Check(naturalMoon.PreAI(),"natural archived soul lifecycle unchanged");
foreach(bool moonKind in new[]{false,true})foreach(int mode in new[]{0,1,2}){
 Reset();Main.player[1].active=true;Terraria.ModLoader.ModNPC owner=moonKind?MoonParent():Parent();Terraria.ModLoader.ModNPC follower=moonKind?MoonChild((MoonboneImmortal)owner):Child((BlackFurnaceIronGolem)owner);owner.NPC.target=1;Main.netMode=mode;int cooldown=0;Check(!follower.CanHitPlayer(Main.player[0],ref cooldown)&&!follower.CanHitNPC(new()),"mismatched summon targets refuse contact immediately");var beforeTargetAge=Save(follower);bool runs=follower.PreAI();Check(runs==(mode!=1)&&follower.NPC.active,"target mismatch waits on client without deleting summon");if(mode==1){Check(Save(follower).SequenceEqual(beforeTargetAge)&&follower.NPC.target==0,"client waits without aging or choosing target");follower.NPC.target=1;Check(follower.PreAI()&&follower.CanHitPlayer(Main.player[1],ref cooldown),"matching authority target packet restores client summon");}else{Check(follower.NPC.target==1&&follower.NPC.netUpdate&&follower.CanHitPlayer(Main.player[1],ref cooldown),"authority aligns and synchronizes summon target");}
}
TribulationCloudAvatar CloudParent(){var boss=new TribulationCloudAvatar();boss.NPC=new(){active=true,life=100,whoAmI=3,target=0,ModNPC=boss};Main.npc[3]=boss.NPC;return boss;}
TribulationCloudling CloudChild(TribulationCloudAvatar boss){var child=new TribulationCloudling();child.NPC=new(){active=true,life=70,whoAmI=4,ModNPC=child};child.OnSpawn(new EntitySource_Parent(boss.NPC));return child;}
foreach(int mode in new[]{0,1,2})foreach(int reason in new[]{0,1,2,3,4,5}){Reset();var boss=CloudParent();var child=CloudChild(boss);Main.netMode=mode;if(reason==0)boss.NPC.active=false;else if(reason==1)Main.player[0].dead=true;else if(reason==2)boss.NPC.target=255;else if(reason==3)child.NPC.Center=new(4001,0);else if(reason==4)child.NPC.velocity=new(float.NaN,0);else{Main.netMode=0;CloudParent();Main.netMode=mode;}int cooldown=0;Check(!child.CanHitPlayer(Main.player[0],ref cooldown),"invalid cloud source contact blocked");Check(!child.PreAI()&&child.NPC.velocity==Microsoft.Xna.Framework.Vector2.Zero,"invalid cloud source freezes");Check(child.NPC.active==(mode==1),"only authority clears cloud summons");Check(NetMessage.Calls==(mode==2?1:0),"cloud cleanup dedicated broadcast");}
Reset();var cloudOwner=CloudParent();var cloudChild=CloudChild(cloudOwner);for(int tick=0;tick<899;tick++)Check(cloudChild.PreAI(),"cloud summon lives before nine hundred ticks");Check(!cloudChild.PreAI()&&!cloudChild.NPC.active&&cloudChild.NPC.damage==0,"cloud expires without death rewards");Reset();cloudOwner=CloudParent();cloudChild=CloudChild(cloudOwner);var cloudWire=Save(cloudChild);Check(cloudWire.Length==13&&Save(cloudOwner).Length==8,"cloud source fixed wire layouts");for(int length=0;length<13;length++){try{Read(cloudChild,cloudWire[..length]);throw new Exception("truncated cloud source accepted");}catch(EndOfStreamException){}Check(Save(cloudChild).SequenceEqual(cloudWire),"cloud truncated source read atomic");}Main.netMode=1;for(int tick=0;tick<1000;tick++)cloudChild.PreAI();Check(Save(cloudChild).SequenceEqual(cloudWire),"cloud client never ages summon");Reset();var naturalCloud=new TribulationCloudling();naturalCloud.OnSpawn(new NaturalSource());Check(naturalCloud.PreAI(),"natural archived soul lifecycle unchanged");

foreach(int mode in new[]{0,1,2}) {
 Reset();Main.player[1].active=true;var boss=CloudParent();var child=CloudChild(boss);boss.NPC.target=1;Main.netMode=mode;int cooldown=0;
 Check(!child.CanHitPlayer(Main.player[0],ref cooldown)&&!child.CanHitNPC(new()),"Cloud target mismatch blocks contact before AI");var before=Save(child);
 Check(child.PreAI()==(mode!=1)&&child.NPC.active,"Cloud target mismatch waits on client and aligns on authority");
 if(mode==1){Check(Save(child).SequenceEqual(before),"Waiting cloud client never ages summon");child.NPC.target=1;}else Check(child.NPC.target==1&&child.NPC.netUpdate,"Authority synchronizes cloud follower target");
 Check(child.PreAI()&&child.CanHitPlayer(Main.player[1],ref cooldown),"Cloud matching target resumes normal AI and contact");
}
Reset();var orderedCloud=CloudParent();var orderedChild=CloudChild(orderedCloud);var parentPacket=Save(orderedCloud);var childPacket=Save(orderedChild);Main.netMode=1;
var remoteCloud=new TribulationCloudAvatar{NPC=orderedCloud.NPC};remoteCloud.NPC.ModNPC=remoteCloud;var remoteCloudChild=new TribulationCloudling{NPC=new(){active=true,life=70}};Read(remoteCloudChild,childPacket);int cloudCooldown=0;
Check(!remoteCloudChild.PreAI()&&!remoteCloudChild.CanHitPlayer(Main.player[0],ref cloudCooldown)&&remoteCloudChild.NPC.active,"Cloud child packet before parent waits harmlessly");Read(remoteCloud,parentPacket);Check(remoteCloudChild.PreAI()&&remoteCloudChild.CanHitPlayer(Main.player[0],ref cloudCooldown),"Late cloud parent session restores client prediction");
for(int length=0;length<8;length++){var before=Save(remoteCloud);try{Read(remoteCloud,parentPacket[..length]);throw new Exception("truncated cloud parent accepted");}catch(EndOfStreamException){}Check(Save(remoteCloud).SequenceEqual(before),"Cloud parent truncated packet atomic");}
{
FormlessSwordSoul SwordParent(){var boss=new FormlessSwordSoul();boss.NPC=new(){active=true,life=100,whoAmI=3,target=0,ModNPC=boss};Main.npc[3]=boss.NPC;return boss;}
ObsessedSwordCultivator SwordChild(FormlessSwordSoul boss){var child=new ObsessedSwordCultivator();child.NPC=new(){active=true,life=70,whoAmI=4,ModNPC=child};child.OnSpawn(new EntitySource_Parent(boss.NPC));return child;}
foreach(int mode in new[]{0,1,2})foreach(int reason in new[]{0,1,2,3,4,5}){Reset();var boss=SwordParent();var child=SwordChild(boss);Main.netMode=mode;if(reason==0)boss.NPC.active=false;else if(reason==1)Main.player[0].dead=true;else if(reason==2)boss.NPC.target=255;else if(reason==3)child.NPC.Center=new(4001,0);else if(reason==4)child.NPC.velocity=new(float.NaN,0);else{Main.netMode=0;SwordParent();Main.netMode=mode;}int cooldown=0;Check(!child.CanHitPlayer(Main.player[0],ref cooldown),"invalid sword source contact blocked");Check(!child.PreAI()&&child.NPC.velocity==Microsoft.Xna.Framework.Vector2.Zero,"invalid sword source freezes");Check(child.NPC.active==(mode==1),"only authority clears sword summons");Check(NetMessage.Calls==(mode==2?1:0),"sword cleanup dedicated broadcast");}
Reset();var swordOwner=SwordParent();var swordChild=SwordChild(swordOwner);for(int tick=0;tick<899;tick++)Check(swordChild.PreAI(),"sword summon lives before nine hundred ticks");Check(!swordChild.PreAI()&&!swordChild.NPC.active&&swordChild.NPC.damage==0,"sword expires without death rewards");Reset();swordOwner=SwordParent();swordChild=SwordChild(swordOwner);var swordWire=Save(swordChild);Check(swordWire.Length==13&&Save(swordOwner).Length==8,"sword source fixed wire layouts");for(int length=0;length<13;length++){try{Read(swordChild,swordWire[..length]);throw new Exception("truncated sword source accepted");}catch(EndOfStreamException){}Check(Save(swordChild).SequenceEqual(swordWire),"sword truncated source read atomic");}Main.netMode=1;for(int tick=0;tick<1000;tick++)swordChild.PreAI();Check(Save(swordChild).SequenceEqual(swordWire),"sword client never ages summon");Reset();var naturalSword=new ObsessedSwordCultivator();naturalSword.OnSpawn(new NaturalSource());Check(naturalSword.PreAI(),"natural sword cultivator lifecycle unchanged");

foreach(int mode in new[]{0,1,2}) {
 Reset();Main.player[1].active=true;var boss=SwordParent();var child=SwordChild(boss);boss.NPC.target=1;Main.netMode=mode;int cooldown=0;
 Check(!child.CanHitPlayer(Main.player[0],ref cooldown)&&!child.CanHitNPC(new()),"Sword target mismatch blocks contact before AI");var before=Save(child);
 Check(child.PreAI()==(mode!=1)&&child.NPC.active,"Sword target mismatch waits on client and aligns on authority");
 if(mode==1){Check(Save(child).SequenceEqual(before),"Waiting sword client never ages summon");child.NPC.target=1;}else Check(child.NPC.target==1&&child.NPC.netUpdate,"Authority synchronizes sword follower target");
 Check(child.PreAI()&&child.CanHitPlayer(Main.player[1],ref cooldown),"Sword matching target resumes normal AI and contact");
}
Reset();var orderedSword=SwordParent();var orderedSwordChild=SwordChild(orderedSword);var swordParentPacket=Save(orderedSword);var swordChildPacket=Save(orderedSwordChild);Main.netMode=1;
var remoteSword=new FormlessSwordSoul{NPC=orderedSword.NPC};remoteSword.NPC.ModNPC=remoteSword;var remoteSwordChild=new ObsessedSwordCultivator{NPC=new(){active=true,life=70}};Read(remoteSwordChild,swordChildPacket);int swordCooldown=0;
Check(!remoteSwordChild.PreAI()&&!remoteSwordChild.CanHitPlayer(Main.player[0],ref swordCooldown)&&remoteSwordChild.NPC.active,"Sword child packet before parent waits harmlessly");Read(remoteSword,swordParentPacket);Check(remoteSwordChild.PreAI()&&remoteSwordChild.CanHitPlayer(Main.player[0],ref swordCooldown),"Late sword parent session restores client prediction");
for(int length=0;length<8;length++){var before=Save(remoteSword);try{Read(remoteSword,swordParentPacket[..length]);throw new Exception("truncated sword parent accepted");}catch(EndOfStreamException){}Check(Save(remoteSword).SequenceEqual(before),"Sword parent truncated packet atomic");}
}
Console.WriteLine($"Furnace summon lifecycle: {checks} checks passed (mock engine boundary).");
