// Missing materials from wiki enemy/boss drop tables
using Terraria;
using Terraria.ID;
using Terraria.ModLoader;

namespace XianXia.Content.Items.HandGenerated;

public class ShatteredJadeShell : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 5); Item.rare = ItemRarityID.White; } }
public class TornTalismanPaper : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 28; Item.height = 24; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 3); Item.rare = ItemRarityID.White; } }
public class CinnabarPowder : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 4); Item.rare = ItemRarityID.White; } }
public class HerbDew : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 8); Item.rare = ItemRarityID.Blue; } }
public class FurnaceCharcoal : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 6); Item.rare = ItemRarityID.White; } }
public class ThunderPatternFeather : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 15); Item.rare = ItemRarityID.LightRed; } }
public class SingingThunderStoneItem : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 20); Item.rare = ItemRarityID.LightRed; } }
public class AbyssDust : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 5); Item.rare = ItemRarityID.Pink; } }
public class DarkBlueSpiritFluid : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 12); Item.rare = ItemRarityID.Pink; } }
public class BrokenSwordIntent : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 30); Item.rare = ItemRarityID.Lime; } }
public class TornScrollPage : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 25); Item.rare = ItemRarityID.Lime; } }
public class BrokenHeavenJade : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 40); Item.rare = ItemRarityID.Yellow; } }
public class BrokenDecreeItem : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 50); Item.rare = ItemRarityID.Yellow; } }
public class ColdMoonDust : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 60); Item.rare = ItemRarityID.Red; } }
public class ArchiveRemnantLight : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 70); Item.rare = ItemRarityID.Red; } }
public class LowGradeSpiritCore : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 99; Item.value = Item.buyPrice(silver: 15); Item.rare = ItemRarityID.Blue; } }
public class SpiritVeinScale : ModItem { public override void SetStaticDefaults() => Item.ResearchUnlockCount = 25; public override void SetDefaults() { Item.width = 32; Item.height = 32; Item.maxStack = 999; Item.value = Item.buyPrice(silver: 10); Item.rare = ItemRarityID.Blue; } }
