using Terraria;
using Terraria.ID;
using Terraria.ObjectData;
using XianXia.Common.Systems;
using XianXia.Content.Tiles;

int assertions=0;
void Check(bool ok,string reason) { assertions++; if(!ok) throw new Exception(reason); }
var crop=new CultivatedSpiritHerbTile();
crop.SetStaticDefaults();
Check(TileObjectData.newTile.AnchorValidTiles.SequenceEqual(new[]{0,2,60,70,71}),"Configured soil anchors include ordinary and cultivation soils.");
Check(TileObjectData.newTile.AnchorAlternateTiles.SequenceEqual(new[]{78,380}),"Pots and planter boxes are supported.");
Check(!TileObjectData.newTile.WaterDeath && TileObjectData.newTile.LavaDeath,"Water pauses rather than destroys; lava destroys.");
Check(crop.CanPlace(0,0),"Empty dry cell can be planted.");
Framing.Cell.LiquidAmount=1;
Check(!crop.CanPlace(0,0),"Cannot plant underwater.");
Framing.Cell=new Tile {HasTile=true,TileType=72};
Check(!crop.CanPlace(0,0),"Cannot overwrite an existing crop.");
Main.netMode=NetmodeID.MultiplayerClient;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==0 && NetMessage.Updates==0,"Client never advances growth or sends its own growth state.");
Main.netMode=NetmodeID.Server;
Framing.Cell.LiquidAmount=1;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==0,"Flooded crop pauses growth.");
Framing.Cell.LiquidAmount=0;
WorldGen.genRand.Grow=false;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==0,"Growth probability may leave the crop unchanged.");
WorldGen.genRand.Grow=true;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==18 && NetMessage.Updates==1,"Server advances and broadcasts the first growth stage.");
var young=crop.GetItemDrops(0,0).ToArray();
Check(young.Length==1 && young[0].type==81 && young[0].stack==1,"Immature harvest refunds exactly one seed and no roots.");
Check(!crop.IsTileSpelunkable(0,0),"Immature crop does not advertise maturity.");
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==36 && NetMessage.Updates==2,"Server advances and broadcasts maturity.");
Check(crop.IsTileSpelunkable(0,0),"Mature crop is visible to spelunker detection.");
var mature=crop.GetItemDrops(0,0).ToArray();
Check(mature.Length==2 && mature[0].type==80 && mature[0].stack==1 && mature[1].type==81 && mature[1].stack==3,"Mature harvest produces a root and replenishes seeds.");
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==36 && NetMessage.Updates==2,"Mature crop stops advancing and sending unchanged updates.");
float r=0,g=0,b=0;
crop.ModifyLight(0,0,ref r,ref g,ref b);
Check(g>r && g>b,"Mature crop emits green light.");
var batch=new Microsoft.Xna.Framework.Graphics.SpriteBatch();
crop.PreDraw(0,0,batch);
Check(batch.LastScale==1f,"Mature plant renders at full size.");
Framing.Cell.TileFrameX=0;
crop.PreDraw(0,0,batch);
Check(batch.LastScale==0.4f,"Seedling has a visibly different rendered size.");
Framing.Cell.HasTile=false;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==0,"Removed crop does not grow back.");
Framing.Cell.HasTile=true;Framing.Cell.TileType=1;
crop.RandomUpdate(0,0);
Check(Framing.Cell.TileFrameX==0,"Growth cannot mutate another tile type.");
for(int stage=0;stage<3;stage++) for(int roll=0;roll<3;roll++) {
 int frame=stage*18;
 Check(SpiritHerbRules.SeedYield(frame,roll)>=1,"Every legitimate harvest preserves replanting ability.");
 Check(SpiritHerbRules.RootYield(frame)==(stage==2?1:0),"Only mature crops produce roots.");
}
Check(SpiritHerbRules.NextFrame(36)==36 && SpiritHerbRules.Stage(-18)==0,"Stage bounds remain valid.");
Console.WriteLine($"Plant lifecycle regression passed: {assertions} assertions against actual tile hooks; engine boundaries mocked.");
