using Terraria;using Microsoft.Xna.Framework;using XianXia.Common.Systems;using System.Reflection;
int assertions=0;void Check(bool ok,string msg){assertions++;if(!ok)throw new Exception(msg);}void Reset(){for(int x=0;x<60;x++)for(int y=0;y<60;y++)Main.tile[x,y]=new();WorldGen.genRand=new();WorldGen.Calls=0;WorldGen.Positions.Clear();WorldGen.Allow=true;}
var type=typeof(GeneratedBiomeWorldGenSystem);var place=type.GetMethod("PlaceObjects",BindingFlags.NonPublic|BindingFlags.Instance);var paint=type.GetMethod("PaintEllipse",BindingFlags.NonPublic|BindingFlags.Static);List<Rectangle> regions=[new(12,12,20,20)];
Reset();for(int x=12;x<32;x++){Main.tile[x,25].HasTile=true;Main.tile[x,25].TileType=88;}var system=new GeneratedBiomeWorldGenSystem();place.Invoke(system,new object[]{77,2,regions,88,3});Check(system.Mod.Logger.InfoMessages[0].Contains("2/2"),"Count complete placed objects");Check(WorldGen.Positions.All(p=>p.X>=12&&p.X+1<32&&p.Y-2>=12&&p.Y<32),"Placement stays in matching region");Check(WorldGen.Positions.Count==2,"Stops after enough complete objects");
Reset();for(int x=12;x<32;x++){Main.tile[x,25].HasTile=true;Main.tile[x,25].TileType=99;}for(int x=12;x<32;x++)for(int y=12;y<32;y++){Main.tile[x,y].HasTile=true;Main.tile[x,y].TileType=99;}system=new();place.Invoke(system,new object[]{77,2,regions,88,3});Check(WorldGen.Calls==0&&system.Mod.Logger.WarnMessages.Count==1,"Wrong biome support rejected and reported");
Reset();for(int x=12;x<32;x++){Main.tile[x,25].HasTile=true;Main.tile[x,25].TileType=88;}WorldGen.Allow=false;system=new();place.Invoke(system,new object[]{77,2,regions,88,3});Check(system.Mod.Logger.InfoMessages[0].Contains("0/2")&&system.Mod.Logger.WarnMessages.Count==1,"Engine failures never counted as success");
Reset();for(int x=12;x<32;x++){Main.tile[x,25].HasTile=true;Main.tile[x,25].TileType=88;Main.tile[x,24].LiquidAmount=255;}for(int x=12;x<32;x++)for(int y=12;y<32;y++){Main.tile[x,y].LiquidAmount=255;}system=new();place.Invoke(system,new object[]{77,2,regions,88,3});Check(WorldGen.Calls==0,"Liquid-filled object space rejected");
Reset();for(int x=10;x<30;x++)for(int y=10;y<30;y++){Main.tile[x,y].HasTile=true;Main.tile[x,y].TileType=2;}int painted=(int)paint.Invoke(null,new object[]{20,20,5,5,100,101,101});Check(painted>0,"Painting reports actual tile count");Check(Main.tile[20,20].WallType==101&&(Main.tile[20,20].TileType==100||Main.tile[20,20].TileType==101),"Tile and wall IDs have independent meaning even when equal");Reset();Check((int)paint.Invoke(null,new object[]{20,20,5,5,100,101,-1})==0,"Empty regions do not pretend to paint ground");
Reset();WorldGen.genRand.LowOnly=true;for(int x=20;x<22;x++){Main.tile[x,25].HasTile=true;Main.tile[x,25].TileType=88;}system=new();place.Invoke(system,new object[]{77,1,regions,88,3});Check(system.Mod.Logger.InfoMessages[0].Contains("1/1")&&WorldGen.Positions.Single()==(20,24),"Exhaustive fallback finds legal ledge missed by every random sample");
var pedestal=type.GetMethod("TryPlacePedestal",BindingFlags.NonPublic|BindingFlags.Static);
Reset();Check((bool)pedestal.Invoke(null,new object[]{77,88,3,20,25})&&Main.tile[20,25].TileType==88,"Empty dry site receives matching pedestal and object");
Reset();Main.tile[20,23].HasTile=true;Main.tile[20,23].TileType=99;Check(!(bool)pedestal.Invoke(null,new object[]{77,88,3,20,25})&&Main.tile[20,23].TileType==99&&!Main.tile[20,25].HasTile,"Pedestal never overwrites occupied site");
Reset();WorldGen.Allow=false;Check(!(bool)pedestal.Invoke(null,new object[]{77,88,3,20,25})&&!Main.tile[20,25].HasTile&&!Main.tile[21,25].HasTile,"Failed object placement removes newly added pedestal");
var passes = new List<Terraria.WorldBuilding.GenPass> { new() { Name="Shinies" }, new() { Name="Cleanup" } }; double weight=0;
system.ModifyWorldGenTasks(passes,ref weight);Check(passes.Last().Name=="XianXia Cultivation Objects","Objects follow every existing terrain/cleanup pass");
Console.WriteLine($"Actual world-generation source regression passed: {assertions} assertions; mocked tile placement boundary, no full world generated.");
