namespace Microsoft.Xna.Framework {public record struct Rectangle(int X,int Y,int Width,int Height){public int Left=>X;public int Right=>X+Width;public int Top=>Y;public int Bottom=>Y+Height;}}
namespace Terraria {public class Tile{public bool HasTile,IsHalfBlock;public ushort TileType,WallType;public byte LiquidAmount,Slope;}public static class Main{public static int maxTilesX=60,maxTilesY=60;public static double worldSurface=20,rockLayer=30;public static Tile[,] tile=new Tile[60,60];}public static class Utils{public static int Clamp(int v,int lo,int hi)=>Math.Clamp(v,lo,hi);}public class Rand{private readonly Random r=new(123);public bool LowOnly;public int Next(int lo,int hi)=>LowOnly?lo:r.Next(lo,hi);public int Next(int max)=>LowOnly?0:r.Next(max);public bool NextBool(int n)=>r.Next(n)==0;}public static class WorldGen{public static Rand genRand=new();public static int Calls;public static bool Allow=true;public static List<(int X,int Y)> Positions=new();public static bool InWorld(int x,int y,int margin)=>x>=margin&&y>=margin&&x<60-margin&&y<60-margin;public static void SquareTileFrame(int x,int y){}public static void PlaceObject(int x,int y,int type){Calls++;Positions.Add((x,y));if(!Allow)return;for(int col=0;col<2;col++)for(int row=0;row<3;row++){Main.tile[x+col,y-row].HasTile=true;Main.tile[x+col,y-row].TileType=(ushort)type;}}}}
namespace Terraria.ID{public static class TileID{public const int Dirt=1,Stone=2,ClayBlock=3,Mud=4,SnowBlock=5,IceBlock=6,Ash=7,Ebonstone=8,Crimstone=9,Pearlstone=10;}}
namespace Terraria.IO{public class GameConfiguration{}}
namespace Terraria.WorldBuilding{public class GenPass{public string Name;}}
namespace Terraria.GameContent.Generation{public class GenerationProgress{public string Message;}public class PassLegacy:Terraria.WorldBuilding.GenPass{public PassLegacy(string name,Action<GenerationProgress,Terraria.IO.GameConfiguration> action){Name=name;}}}
namespace Terraria.Localization{public static class Language{public static string GetTextValue(string key)=>key;}}
namespace Terraria.ModLoader{public class Logger{public List<string> InfoMessages=new(),WarnMessages=new();public void Info(string msg)=>InfoMessages.Add(msg);public void Warn(string msg)=>WarnMessages.Add(msg);}public class Mod{public Logger Logger=new();}public class ModSystem{public Mod Mod=new();public virtual void ModifyWorldGenTasks(List<Terraria.WorldBuilding.GenPass> t,ref double weight){}}public static class ModContent{public static int TileType<T>()=>42;public static int WallType<T>()=>43;public static T GetInstance<T>() where T:new()=>new();}}
namespace XianXia{public class XianXiaConfig{public bool EnableWorldGeneration=true;}}
namespace XianXia.Content.Tiles{public class GreenwoodSoilTile{}public class SpiritHerbTile{}public class FurnaceSlagTile{}public class BlackFurnaceWall{}public class ThunderCloudTile{}public class StarAbyssCrystalTile{}public class SectRuinBrickTile{}public class FallenHeavenJadeTile{}public class MoonboneTile{}public class SwordTabletTile{}public class SingingThunderStoneTile{}public class RiftMembraneTile{}public class BrokenHeavenTabletTile{}public class ArchiveLightPillarTile{}}
