using Terraria;using Terraria.ID;using XianXia.Content.NPCs.Bosses;
int checks=0;void Check(bool ok,string name){checks++;if(!ok)throw new Exception(name);}
SpiritVeinWyrm Setup(int planned=2){Main.netMode=2;Main.player=[new(),new(){active=false}];Main.npc=Enumerable.Range(0,Main.maxNPCs).Select(i=>new NPC{whoAmI=i}).ToArray();Main.rand=new(){Planned=planned};NPC.Calls=NPC.FailureAt=0;NPC.FailureResult=int.MinValue;var boss=new SpiritVeinWyrm();boss.NPC=Main.npc[0];boss.NPC.active=true;boss.NPC.type=9;boss.NPC.target=0;return boss;}
foreach(int planned in new[]{2,3}){
 var boss=Setup(planned);boss.SpawnSplitMinions(true);Check(NPC.Calls==planned,"chosen quota created");foreach(var child in Main.ActiveNPCs.Where(n=>n.type==7))Check(child.target==0&&child.ai[0]==0&&child.netUpdate,"successful spawn has target/source/sync");
 foreach(var child in Main.ActiveNPCs.Where(n=>n.type==7).ToArray())child.active=false;for(int tick=0;tick<1000;tick++)boss.SpawnSplitMinions(true);Check(NPC.Calls==planned,"killed quota never replenished");
 boss=Setup(planned);foreach(var slot in Main.npc.Skip(1))slot.active=true;boss.SpawnSplitMinions(true);Check(NPC.Calls==0&&Main.rand.Calls==1,"full table preflight rolls quota once and creates nothing");foreach(var slot in Main.npc.Skip(1))slot.active=false;
 for(int tick=1;tick<60;tick++)boss.SpawnSplitMinions(true);Check(NPC.Calls==0&&Main.rand.Calls==1,"cooldown has no spawn or repeated quota RNG");boss.SpawnSplitMinions(true);Check(NPC.Calls==planned,"exact sixty-tick retry after capacity frees");
 boss=Setup(planned);NPC.FailureAt=2;NPC.FailureResult=Main.maxNPCs;boss.SpawnSplitMinions(true);Check(NPC.Calls==2&&Main.ActiveNPCs.Count(n=>n.type==7)==1,"partial creation counted before failure");NPC.FailureResult=int.MinValue;for(int tick=0;tick<60;tick++)boss.SpawnSplitMinions(true);Check(Main.ActiveNPCs.Count(n=>n.type==7)==planned&&NPC.Calls==planned+1,"retry fills only missing quota");
 for(int free=0;free<=18;free++){boss=Setup(planned);for(int index=free+1;index<Main.maxNPCs;index++)Main.npc[index].active=true;boss.SpawnSplitMinions(true);Check(NPC.Calls==(free>=planned*6?planned:0),"head plus full chain capacity boundary");}
}
foreach(int failure in new[]{-1,Main.maxNPCs,int.MaxValue}){var boss=Setup();NPC.FailureResult=failure;boss.SpawnSplitMinions(true);Check(NPC.Calls==1,"bad creation result stops batch");NPC.FailureResult=int.MinValue;for(int tick=0;tick<60;tick++)boss.SpawnSplitMinions(true);Check(Main.ActiveNPCs.Count(n=>n.type==7)==2,"bad creation result preserves pending quota");}
foreach(Action<SpiritVeinWyrm> invalid in new Action<SpiritVeinWyrm>[] {b=>Main.netMode=1,b=>b.NPC.active=false,b=>b.NPC.life=0,b=>b.NPC.target=255,b=>Main.player[0].dead=true,b=>Main.player[0].Center=new(5000,0),b=>b.NPC.Center=new(float.NaN,0)}){var boss=Setup();invalid(boss);boss.SpawnSplitMinions(true);Check(NPC.Calls==0&&Main.rand.Calls==0,"invalid battle/client does not consume quota or RNG");}
var phase=Setup();phase.SpawnSplitMinions(false);Check(NPC.Calls==0&&Main.rand.Calls==0,"first phase has no quota RNG");
var wrong=Setup();NPC.FailureResult=0;wrong.SpawnSplitMinions(true);Check(NPC.Calls==1&&!wrong.NPC.netUpdate,"returned unrelated NPC not modified");NPC.FailureResult=int.MinValue;for(int tick=0;tick<60;tick++)wrong.SpawnSplitMinions(true);Check(Main.ActiveNPCs.Count(n=>n.type==7)==2,"wrong-type return preserves quota");
var congested=Setup();foreach(var slot in Main.npc.Skip(1))slot.active=true;for(int tick=0;tick<1200;tick++)congested.SpawnSplitMinions(true);Check(NPC.Calls==0&&Main.rand.Calls==1,"persistent capacity failure never rerolls or invokes spawner");
Console.WriteLine($"Wyrm split retry: {checks} checks passed; native creation/transport mocked.");
