using Microsoft.Xna.Framework;
using Terraria;
using Terraria.ModLoader;
using XianXia.Content.Projectiles;
using XianXia.Content.Buffs;
using XianXia.Content.Items.HandGenerated;
using Game=Terraria.Main;
int assertions=0;
void Check(bool condition,string message){assertions++;if(!condition)throw new Exception(message);}
SmallArtifactSpirit Setup(){
 Game.myPlayer=0;Game.dedServ=false;Game.player[0]=new Player {Buff=true};Game.player[1]=new Player {whoAmI=1,Buff=true};
 foreach(var npc in Game.npc)npc.active=false;foreach(var p in Game.projectile)p.active=false;
 Collision.Visible=true;Projectile.AllowSpawn=true;var spirit=new SmallArtifactSpirit();spirit.SetDefaults();return spirit;
}
var spirit=Setup();spirit.SetStaticDefaults();
Check(spirit.Projectile.minionSlots==1&&ReferenceEquals(spirit.Projectile.DamageType,DamageClass.Summon)&&Game.projPet[1],"A real minion occupies one slot and uses summon damage.");
Check(spirit.MinionContactDamage()&&spirit.CanCutTiles()==false&&!spirit.Projectile.tileCollide,"Contact damage is enabled without cutting or collision trapping.");
spirit.AI();Check(!spirit.Projectile.friendly&&spirit.Projectile.velocity.X<0&&spirit.Projectile.velocity.Y<0,"Idle spirits return behind the owner without damaging.");
spirit=Setup();Game.npc[0].active=true;Game.npc[0].Center=new(100,0);spirit.AI();Check(spirit.Projectile.friendly&&spirit.Projectile.velocity.X>0,"A visible valid enemy is chased.");
spirit=Setup();Game.npc[0].active=true;Game.npc[0].Center=new(100,0);Collision.Visible=false;spirit.AI();Check(!spirit.Projectile.friendly,"Blocked targets do not cause attacks through walls.");
spirit=Setup();Game.npc[0].active=true;Game.npc[0].Center=new(701,0);spirit.AI();Check(!spirit.Projectile.friendly,"Enemies outside the owner's target range are ignored.");
spirit=Setup();Game.npc[0].active=true;Game.npc[0].chaseable=false;Game.npc[0].Center=new(50,0);spirit.AI();Check(!spirit.Projectile.friendly,"Friendly and unchaseable NPCs are ignored.");Game.npc[0].chaseable=true;
spirit=Setup();Game.npc[0].active=Game.npc[1].active=true;Game.npc[0].Center=new(50,0);Game.npc[1].Center=new(-100,0);
Game.player[0].HasMinionAttackTargetNPC=true;Game.player[0].MinionAttackTargetNPC=1;spirit.AI();Check(spirit.Projectile.velocity.X<0,"A valid selected target takes priority over nearer enemies.");
spirit=Setup();spirit.Projectile.Center=new(1700,0);spirit.AI();Check(spirit.Projectile.Center==new Vector2(-40,-48)&&spirit.Projectile.netUpdate,"The owner teleports a distant spirit back and requests synchronization.");
spirit=Setup();Game.myPlayer=1;spirit.Projectile.Center=new(1700,0);spirit.AI();Check(spirit.Projectile.Center==new Vector2(1700,0)&&!spirit.Projectile.netUpdate,"Other clients do not issue competing teleports.");
spirit=Setup();Game.player[0].Buff=false;spirit.AI();Check(!spirit.Projectile.active,"Canceling the owner's buff ends the minion.");
spirit=Setup();Game.myPlayer=1;Game.player[0].Buff=false;spirit.AI();Check(spirit.Projectile.active&&!spirit.Projectile.friendly&&spirit.Projectile.timeLeft==180,"First-time observers wait for buff synchronization without attacking.");
spirit=Setup();Game.player[0].dead=true;spirit.AI();Check(!spirit.Projectile.active,"Death ends the minion.");
spirit=Setup();Game.player[0].active=false;spirit.AI();Check(!spirit.Projectile.active,"Disconnecting ends the minion.");
spirit=Setup();Game.dedServ=true;int lights=Lighting.Calls;spirit.AI();Check(Lighting.Calls==lights,"Dedicated servers do not execute the visual lighting effect.");
var buff=new SmallArtifactSpiritBuff();buff.SetStaticDefaults();Check(Game.buffNoSave[2]&&Game.buffNoTimeDisplay[2],"The minion buff is not persisted or timed visually.");
Setup();int slot=0;Game.player[0].ownedProjectileCounts[1]=1;buff.Update(Game.player[0],ref slot);Check(Game.player[0].buffTime[0]==18000,"Owned minions maintain the buff.");
Game.player[0].ownedProjectileCounts[1]=0;buff.Update(Game.player[0],ref slot);Check(!Game.player[0].Buff&&slot==-1,"Missing minions clear their buff correctly.");
Setup();var pendant=new SmallArtifactPendant();pendant.SetDefaults();Check(pendant.CanUseItem(Game.player[0]),"A free slot allows summoning.");
Game.player[0].slotsMinions=1;Check(!pendant.CanUseItem(Game.player[0]),"Full minion capacity prevents summoning.");
Setup();Game.projectile[0]=new Projectile {active=true,owner=0,type=1};Check(!pendant.CanUseItem(Game.player[0]),"Existing owned spirits prevent duplicates.");
Game.projectile[0].owner=1;Check(pendant.CanUseItem(Game.player[0]),"Another player's spirit does not occupy the owner's type cap.");
foreach(var p in Game.projectile)p.active=true;Check(!pendant.CanUseItem(Game.player[0]),"A full projectile pool prevents summoning.");
Setup();pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);Check(Game.projectile[0].active&&Game.projectile[0].originalDamage==12&&Game.projectile[0].damage==18&&Game.player[0].Buff,"The owner's actual summon retains base and computed damage plus the buff.");
Setup();Game.player[0].Buff=false;Projectile.AllowSpawn=false;pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);Check(!Game.player[0].Buff&&!Game.ActiveProjectiles.Any(),"Spawn failure does not create a phantom buff.");
Setup();Game.myPlayer=1;pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);Check(!Game.ActiveProjectiles.Any(),"Observers and dedicated servers cannot duplicate the owner's summon.");
Setup();pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);
Check(Game.ActiveProjectiles.Count()==1,"Reentrant shoot calls cannot bypass the one-spirit cap.");
Setup();Check(pendant.CanUseItem(Game.player[0]),"Preflight initially succeeds.");Game.player[0].slotsMinions=1;pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);
Check(!Game.ActiveProjectiles.Any(),"A slot consumed after preflight blocks the final summon.");
Setup();Game.player[0].dead=true;pendant.Shoot(Game.player[0],null,Vector2.Zero,Vector2.Zero,1,18,0);
Check(!Game.ActiveProjectiles.Any(),"Death between preflight and shooting cannot create a minion.");
Setup();Game.player[0].Buff=false;spirit= new SmallArtifactSpirit();spirit.SetDefaults();Game.myPlayer=255;Game.dedServ=true;spirit.AI();
Check(spirit.Projectile.active&&!spirit.Projectile.friendly&&spirit.Projectile.timeLeft==180,"The dedicated server waits for the initial owner buff sync without killing or attacking.");
Console.WriteLine($"Companion lifecycle regression passed: {assertions} assertions against actual item/buff/projectile hooks; engine boundaries mocked.");
