namespace Microsoft.Xna.Framework { public record struct Vector2(float X,float Y){public static Vector2 Zero=>new(0,0);public static Vector2 operator +(Vector2 a,Vector2 b)=>new(a.X+b.X,a.Y+b.Y);public static Vector2 operator *(Vector2 a,float b)=>new(a.X*b,a.Y*b);} public record struct Rectangle(int X,int Y,int Width,int Height); public struct Color{public static Color MediumPurple=>new();public static Color operator *(Color c,float value)=>c;} public static class MathHelper{public static float Lerp(float a,float b,float t)=>a+(b-a)*t;} }
namespace Terraria { public class Projectile {public int width,height,penetrate,timeLeft,alpha,damage,owner;public bool hostile,friendly,tileCollide,ignoreWater,hide,netImportant,netUpdate;public float rotation;public Microsoft.Xna.Framework.Vector2 position,Center,velocity;public object GetSource_FromThis()=>null;public static int Spawned;public static int NewProjectile(object source,Microsoft.Xna.Framework.Vector2 p,Microsoft.Xna.Framework.Vector2 v,int type,int damage,float knockback,int owner){Spawned++;return 0;}}public class Player{public bool active=true,dead;public Microsoft.Xna.Framework.Vector2 Center; public int BuffCalls,Duration;public struct HurtInfo{} public void AddBuff(int type,int time){BuffCalls++;Duration=time;}}public static class Main { public static int netMode;public static bool dedServ;public static RandomStub rand=new();public static Microsoft.Xna.Framework.Vector2 screenPosition;public static Microsoft.Xna.Framework.Graphics.SpriteBatch spriteBatch=new();}public class RandomStub{public int Calls;public bool NextBool(int n){Calls++;return true;}}public class Dust{public bool noGravity;public Microsoft.Xna.Framework.Vector2 velocity;public static int Calls;public static Dust NewDustDirect(Microsoft.Xna.Framework.Vector2 p,int w,int h,int type){Calls++;return new();}}public static class Collision{public static bool Blocked;public static bool CanHitLine(Microsoft.Xna.Framework.Vector2 a,int w,int h,Microsoft.Xna.Framework.Vector2 b,int w2,int h2)=>!Blocked;}public static class Lighting{public static int Calls;public static void AddLight(Microsoft.Xna.Framework.Vector2 p,float r,float g,float b)=>Calls++;}}
namespace Terraria.ID{public static class DustID{public const int GemAmethyst=1,Electric=2;}public static class NetmodeID{public const int MultiplayerClient=1,Server=2;}}
namespace Terraria.ModLoader{public class ModProjectile{public Terraria.Projectile Projectile=new();public virtual string Texture=>"";public virtual void SetDefaults(){}public virtual void AI(){}public virtual bool? CanDamage()=>null;public virtual void OnHitPlayer(Terraria.Player p,Terraria.Player.HurtInfo i){}public virtual void OnKill(int timeLeft){}public virtual bool CanHitPlayer(Terraria.Player p)=>true;public virtual void SendExtraAI(System.IO.BinaryWriter w){}public virtual void ReceiveExtraAI(System.IO.BinaryReader r){}public virtual bool PreDraw(ref Microsoft.Xna.Framework.Color c)=>true;}public static class ModContent{public static int BuffType<T>()=>1;public static int ProjectileType<T>()=>2;}}
namespace XianXia.Content.Buffs{public class SpiritualPressureDisorderBuff{}}
namespace XianXia.Content.Projectiles{public class TribulationLightningProjectile{}}

namespace Microsoft.Xna.Framework.Graphics { public class SpriteBatch{public List<Microsoft.Xna.Framework.Rectangle> Boxes=new();public void Draw(object texture,Microsoft.Xna.Framework.Rectangle box,Microsoft.Xna.Framework.Color color)=>Boxes.Add(box);} }
namespace Terraria.GameContent {public static class TextureAssets{public static Asset MagicPixel=new();public class Asset{public object Value=>new();}}}
