namespace Terraria.Localization {public record LocalizedText(string Key,string Value);public static class Language {public static Dictionary<string,string> Values=new();public static LocalizedText GetText(string key)=>new(key,Values.GetValueOrDefault(key,key));}}
namespace Terraria.ModLoader {
public class LoggerStub {public List<string> Warnings=new(),Infos=new();public void Warn(string text)=>Warnings.Add(text);public void Info(string text)=>Infos.Add(text);}
public class Mod {public Version Version=new(2,2,4);public LoggerStub Logger=new();public List<object[]> Calls=new();public bool ThrowFirst,RejectFirst;public virtual object Call(params object[] args){Calls.Add(args);if(Calls.Count==1&&ThrowFirst)throw new InvalidOperationException("External API failure");return Calls.Count==1&&RejectFirst?"Failure":"Success";}}
public class ModSystem {public Mod Mod=new();public virtual void PostSetupContent(){}public virtual void Unload(){}}
public class ModNPC{}public class ModItem{}
public static class ModLoader {public static Mod Checklist;public static bool TryGetMod(string name,out Mod mod){mod=name=="BossChecklist"?Checklist:null;return mod!=null;}}
public static class ModContent {public static XianXia.Common.Systems.XianXiaConfig Config=new();private static Dictionary<Type,int> ids=new();public static int Id(Type type){if(!ids.ContainsKey(type))ids[type]=100+ids.Count;return ids[type];}public static T GetInstance<T>()=>(T)(object)Config;public static int NPCType<T>() where T:ModNPC=>Id(typeof(T));public static int ItemType<T>() where T:ModItem=>Id(typeof(T));public static string Name(int id)=>ids.Single(p=>p.Value==id).Key.Name;}
}
namespace XianXia.Common.Systems {public class XianXiaConfig {public bool EnableSoftCompatibilityHooks=true;}public static class DownedBossSystem {public static HashSet<string> DownedBosses=new();}}
namespace XianXia.Content.NPCs.Bosses {public class SpiritVeinWyrm : Terraria.ModLoader.ModNPC{}public class GardenWarden : Terraria.ModLoader.ModNPC{}public class BlackFurnaceIronGolem : Terraria.ModLoader.ModNPC{}public class TribulationCloudAvatar : Terraria.ModLoader.ModNPC{}public class ThunderMarshJiao : Terraria.ModLoader.ModNPC{}public class AbyssalStarWomb : Terraria.ModLoader.ModNPC{}public class FormlessSwordSoul : Terraria.ModLoader.ModNPC{}public class GreenwoodMedicineKingEcho : Terraria.ModLoader.ModNPC{}public class HeavenTabletGuardian : Terraria.ModLoader.ModNPC{}public class BrokenHeavenInspector : Terraria.ModLoader.ModNPC{}public class MoonboneImmortal : Terraria.ModLoader.ModNPC{}public class OldHeavenDaoCore : Terraria.ModLoader.ModNPC{}}
namespace XianXia.Content.Items.BossSummons {public class SpiritVeinIncense : Terraria.ModLoader.ModItem{}public class SummonGardenBrokenKey : Terraria.ModLoader.ModItem{}public class SummonOldFurnaceEmber : Terraria.ModLoader.ModItem{}public class SummonThunderCallingJade : Terraria.ModLoader.ModItem{}public class SummonThunderCallingJadeThunderMarshJiao : Terraria.ModLoader.ModItem{}public class SummonStarAbyssMembrane : Terraria.ModLoader.ModItem{}public class SummonSectTrialToken : Terraria.ModLoader.ModItem{}public class SummonSectTrialTokenGreenwoodMedicineKingEcho : Terraria.ModLoader.ModItem{}public class SummonHeavenTabletRubbing : Terraria.ModLoader.ModItem{}public class SummonHeavenTabletRubbingBrokenHeavenInspector : Terraria.ModLoader.ModItem{}public class SummonMoonboneRitualTalisman : Terraria.ModLoader.ModItem{}public class SummonMoonboneRitualTalismanOldHeavenDaoCore : Terraria.ModLoader.ModItem{}}
namespace XianXia.Content.Items.MasterRewards {public class SpiritVeinWyrmMonument : Terraria.ModLoader.ModItem{}public class GardenWardenMonument : Terraria.ModLoader.ModItem{}public class BlackFurnaceIronGolemMonument : Terraria.ModLoader.ModItem{}public class TribulationCloudAvatarMonument : Terraria.ModLoader.ModItem{}public class ThunderMarshJiaoMonument : Terraria.ModLoader.ModItem{}public class AbyssalStarWombMonument : Terraria.ModLoader.ModItem{}public class FormlessSwordSoulMonument : Terraria.ModLoader.ModItem{}public class GreenwoodMedicineKingEchoMonument : Terraria.ModLoader.ModItem{}public class HeavenTabletGuardianMonument : Terraria.ModLoader.ModItem{}public class BrokenHeavenInspectorMonument : Terraria.ModLoader.ModItem{}public class MoonboneImmortalMonument : Terraria.ModLoader.ModItem{}public class OldHeavenDaoCoreMonument : Terraria.ModLoader.ModItem{}}
namespace XianXia.Content.Items.HandGenerated {public class SpiritVeinWyrmTrophy : Terraria.ModLoader.ModItem{}public class GardenWardenMask : Terraria.ModLoader.ModItem{}public class BlackFurnaceIronGolemPet : Terraria.ModLoader.ModItem{}public class AbyssalStarWombLamp : Terraria.ModLoader.ModItem{}public class FormlessSwordSoulCostume : Terraria.ModLoader.ModItem{}public class SmallTabletPet : Terraria.ModLoader.ModItem{}public class InspectorMask : Terraria.ModLoader.ModItem{}}
